### ISSUE TITLE
BUG: 2.3-Alpha Not all Group:GetVelocity() methods seem to be functioning.

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#798] opened 2018-01-27 22:04 UTC
Group:GetVelocity() functions don't appear to be working correctly, GetVelocityKMH is throwing an error due to what appears to be a case issue (see below)

```01028.256 INFO    SCRIPTING:     96(    -1)/E:                BASE00000.function(OVERLORD VELOCITY CHECK)
01028.257 INFO    SCRIPTING:     97(    -1)/E:                BASE00000.function({[1]={[Velocity]={[ClassName]=GROUP,[GroupName]=OVERLORD,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},},[ClassName]=VELOCITY,},})
01028.257 INFO    SCRIPTING:     98(    -1)/E:                BASE00000.function(OVERLORD VELOCITY CHECK KMH)
01028.257 INFO    SCRIPTING: Error in timer function: [string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:23998: attempt to call method 'getVelocity' (a nil value)
01028.257 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:4769: in function 'getVelocity'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:23998: in function 'GetVelocityVec3'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:24040: in function 'GetVelocityKMH'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00002136"]:99: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00002136"]:94>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:4809: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis0000273E"]:4763>
01028.257 INFO    SCRIPTING:    169(    -1)/E:                BASE00000.function({[1]=No violation recorded.,})
```

looking at moose this appears to be linked to:

local PositionableVelocityVec3 = DCSPositionable:getVelocity()

in function 

unction POSITIONABLE:GetVelocityVec3()
  self:F2( self.PositionableName )

  local DCSPositionable = self:GetDCSObject()
  
  if DCSPositionable then
    local PositionableVelocityVec3 = DCSPositionable:getVelocity()
    self:T3( PositionableVelocityVec3 )
    return PositionableVelocityVec3
  end
  
  BASE:E( { "Cannot GetVelocityVec3", Positionable = self, Alive = self:IsAlive() } )

  return nil
end

the G should be capitalised.

**Comment by robgrahamau** [comment] 2018-01-27 22:30
Even after changing g to G it still errors the actual error is happening in GetVelocityVec3 which is used by all the other methods. 

Specifically   
` local PositionableVelocityVec3 = DCSPositionable:getVelocity() `
doesn't matter if it's done as that or as 
` local PositionableVelocityVec3 = DCSPositionable:GetVelocity() `

**Comment by FlightControl-User** [comment] 2018-02-18 10:51
@robgrahamau getVelocity() is a DCS API method. The method GetVelocityKMH should work correctly.
I think the issue is that you have a GROUP. It is a bug, and I need to provide a fix, try however to do the following...

Try to get the first unit of the group and then call the GetVelocityKMH() method.

Maybe that will fix it.
Please let me know.

**Comment by FlightControl-User** [comment] 2018-03-03 06:08
I haven't got any feedback on this, and I know that GetVelocity works so closing this one.

**Closed by FlightControl-User** 2018-03-03 06:08 UTC
Labels: enhancement, ready for testing, workaround
