### ISSUE TITLE
formation parameter not followed by AI in CONTROLLABLE:TaskRouteToZone

### ISSUE THREAD

**Issue by Kalbuth** [FlightControl-Master/MOOSE#306] opened 2017-03-13 21:35 UTC
It seems that when building the 2 waypoints for a TaskRouteToZone, the function forces the initial waypoint to have a "Cone" formation (in PointFrom.action, Controllable.lua line 1592)
This make it so that Controllable doesn't use the enforced formation. PointFrom.action should be set to the Formation parameter, apparently (tested and it indeed works)
diff : 
@@ -1589,7 +1589,7 @@ function CONTROLLABLE:TaskRouteToZone( Zone, Randomize, Speed, Formation )
    PointFrom.x = ControllablePoint.x
    PointFrom.y = ControllablePoint.y
    PointFrom.type = "Turning Point"
    PointFrom.action = "Cone"
    PointFrom.action = Formation or "Cone"
    PointFrom.speed = 20 / 1.6

The Git noob that I am doesn't know how to push/pull the fix for approval ( since I don't use my local fork anymore, perhaps that's the issue?)

**Comment by FlightControl-Master** [comment] 2017-03-14 04:45
check your message on slack to get the fix in

**Comment by FlightControl-Master** [comment] 2017-03-23 19:51
wasn't this fixed????

**Comment by FlightControl-Master** [comment] 2017-03-23 19:52
@Kalbuth wasn't this fixed?

**Comment by thebgpikester** [comment] 2017-03-25 11:48
Still need feedback from reporter on if this is fixed. Is there a Slack username we can ping?

**Comment by thebgpikester** [comment] 2017-03-25 11:50
Removed the Urget flag as a fix has been offered.

**Comment by FlightControl-Master** [comment] 2017-03-25 14:39
@Kalbuth can this he tested or confirmed fixed?

**Comment by Grey-Echo** [comment] 2017-03-25 23:52
I tested this issue with the following code, and variating the formation string: 
`myGr = GROUP:FindByName("GROUP")`
`myGr:TaskRouteToZone( ZONE:New( "Zone" ), true, 40, "Vee" )`
The group took the Vee formation, or any other I assigned them, since the beginning, and until they reached the Zone. It worked flawlessly, apart from the abysmal DCS AI.
So I think it is time to close this issue !

**Closed by Grey-Echo** 2017-03-25 23:52 UTC
Labels: bug, help wanted, question, ready for testing
