### ISSUE TITLE
Error Re-spawning Tanker. 

### ISSUE THREAD

**Issue by DeadStick200** [FlightControl-Master/MOOSE#989] opened 2018-09-22 03:59 UTC
Shell_KC130 = SPAWN:New( "KC130" )
  :InitLimit(1,10)
  :InitRepeatOnLanding()
  :SpawnScheduled(30,0)

Note: Moose 2.2 this works/ Moose 2.4 Does this error

ERROR Code--
2018-09-21 19:06:44.401 INFO    SCRIPTING:   6075(    13)/E:               EVENT00000.onEvent({[1]=S_EVENTLAND,[2]={[IniUnit]={[ClassName]=UNIT,[UnitName]=KC130#001-01,},[place]={[id]=5000026,},[IniUnitName]=KC130#001-01,[time]=29978.081,[IniGroup]={[ClassName]=GROUP,[GroupName]=KC130#001,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},},[IniDCSGroupName]=KC130#001,[IniCoalition]=2,[id]=4,[IniObjectCategory]=1,[IniTypeName]=KC130,[subPlace]=0,[IniCategory]=0,[IniGroupName]=KC130#001,[initiator]={[id]=16795392,},[IniDCSUnitName]=KC130#001-01,[IniDCSUnit]=,[IniDCSGroup]={[id]=1001028,},},[3]=KC130#001-01,[5]=1,})
2018-09-21 19:06:44.401 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:21985: attempt to index local 'SpawnGroup' (a nil value)
2018-09-21 19:06:44.401 INFO    SCRIPTING: stack traceback:
    [string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:5914: in function <[string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:5910>
    [string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:21985: in function 'ReSpawn'
    [string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:23502: in function <[string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:23488>
    (tail call): ?
    [C]: in function 'xpcall'
    [string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00007248"]:6204: in function 'onEvent'
    [string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

**Comment by Delta-99** [comment] 2018-09-25 16:28
Might be a duplicate of #939

**Comment by FlightControl-User** [comment] 2018-09-29 10:47
@DeadStick200 sorry, but I cannot simulate this issue. I don't know. I'll upload a test mission.

**Comment by FlightControl-User** [comment] 2018-09-30 05:36
@DeadStick200 dead Please check this test mission:

https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/SPA%20-%20Spawning/SPA-120%20-%20Air%20Ops%20-%20Scheduled%20Spawn%20with%20Repeat%20on%20Landing%20with%20Limit

Please test, and if you can resimulate the issue again, please repost the error (here in this post), reopen the issue and please explain:
- How long was the mission active?
- Where are the planes spawned (which airbase, which spot)?
- Was there another airplane blocking the spot in the base?

This is a very difficult thing to resimulate, and i can't keep this issue open. so, if you can resimulate, please post your findings here and i'll check with you in detail.

**Closed by FlightControl-User** 2018-09-30 05:36 UTC
Labels: can't reproduce, possible bug, urgent (fix in a few days)
