### ISSUE TITLE
'Unit doesn't exist' in ScanObjects

### ISSUE THREAD

**Issue by RedMeKool** [FlightControl-Master/MOOSE#1334] opened 2020-06-05 16:25 UTC
When using the 'SpawnAtAirbase' function I occasionally get the following error in my log:

```
2020-06-05 16:02:17.069 INFO    SCRIPTING: Error in timer function: [string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:19722: Unit doesn't exist
2020-06-05 16:02:17.069 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:6076: in function <[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:6073>
	[C]: in function 'getName'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:19722: in function 'ScanObjects'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:41080: in function 'FindFreeParkingSpotForAircraft'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:27422: in function 'SpawnAtAirbase'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00004A42.lua"]:197: in function 'spawnTRANSPORT'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00004A42.lua"]:169: in function <[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00004A42.lua"]:112>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:6129: in function <[string "C:\Users\remko\AppData\Local\Temp\DCS\/~mis00002EE0.lua"]:6065>
```

This line in the MOOSE code is throwing a Unit doesn't exist error:
self:T(string.format("Scan found static %s", static:getName()))

Using MOOSE version:
env.info( '*** MOOSE GITHUB Commit Hash ID: 2020-05-19T07:41:18.0000000Z-27de274b6ec30b396ac4f4b4e20c23ceae0d2ac6 ***' )

**Comment by funkyfranky** [comment] 2020-06-05 16:29
Do you have any statics in the area? I guess for some statics the getName function does not work.

**Comment by RedMeKool** [comment] 2020-06-05 16:48
> Do you have any statics in the area? I guess for some statics the getName function does not work.

No, at least not placed by me. I am spawning transport planes on random airfields on the default and unedited Persian Gulf map.

**Comment by funkyfranky** [comment] 2020-06-05 19:55
Strange as the scan finds a static. Are you also spawning on the super carrier? Because I think the deck crew are static objects and the getName function does not work for them.

**Comment by RedMeKool** [comment] 2020-06-05 21:57
> Strange as the scan finds a static. Are you also spawning on the super carrier? Because I think the deck crew are static objects and the getName function does not work for them.

 Nope, there is no carrier present in the mission (yet)

**Comment by funkyfranky** [comment] 2020-06-05 22:10
Then I don't know. Do you have a simple test mission where this happens so I can check myself?

**Comment by RedMeKool** [comment] 2020-06-06 07:21
I tried to make an example mission but I can’t really reproduce the error. I only occassionally get the error in the mission I’m building. I have updated tor the latest MOOSE version to see if this makes any difference. Could it be that a wreck of a destroyed airplane on the tarmac/runway is considered a static nameless object?

**Comment by RedMeKool** [comment] 2020-06-07 19:07
Just A small update. I'm pretty convinced it is caused by a burning wreck that is being considered a static. Is there a way I can prevent this error, because it is stopping a function that is supposed to be running.

**Comment by funkyfranky** [comment] 2020-06-11 19:57
Thanks for your mission @RedMeKool. I ran it for 3 hours in accelerated time but was not able to capture the bug yet.

To my knowledge, wrecks (dead units) are not treated as statics in DCS. If so, this is new and would actually be a good thing many of us have long asked for.

I am starting to think it could be **ejected pilots**. A recent change in DCS was that these are represented as statics now. However, the DCS implementation is sloppy and many functions (like :getName()) do not work for ejected pilots as they do for normal statics.

In any case, this is certainly a DCS bug which needs to be reported and fixed by ED. I could comment out the line that causes the error you describe, but then the error would probably occur at another point.

**Comment by RedMeKool** [comment] 2020-06-12 18:09
Thank you for your reply. Although it would be godsend if ED fixed the wrecks issue in DCS, I think you are right regarding ejected pilots considered as static. I added a ~= nil check in the MOOSE function and seems to prevent the error and keeps my functions running. 
2 questions:
- Do you report this as a bug to ED?
- Is there another workaround possible?

**Comment by funkyfranky** [comment] 2020-06-13 18:45
Well, I am surprised that a nil check works for you because:
- the loop should only go over objects that are not nil. A nil check is performed before.
- The error message would be different.
- If this is really an ejected pilot, the static object is not nil. it's just the getName function not working on it.

**Comment by RedMeKool** [comment] 2020-06-18 17:43
I only check if the static:getName() call is nil. Like this:
`    for _,static in pairs(Statics) do
		if static:getName() ~= nil then
		  self:T(string.format("Scan found static %s", static:getName()))
		  _DATABASE:AddStatic(static:getName())
		end`

So far I haven't seen the error pop up anymore, even after running for a long time.
However this could of course be coincidence, because it only happens when a pilots ejects.

**Comment by thebgpikester** [comment] 2020-06-25 18:29
How does SpawnAtAirbase() handle "non addressable" static item types"?

What I mean by those is that several statics appear in DCS that you cannot do getName() or getLife() or getID() or other methods on. Such examples include BigSmoke, AIrbases/farps, static ships to an extent, in various ways.

Sure, there may be transient odd items in the scan. Also, test this on both types of dedicated server because sure as hell if soemthing will go tits up it will be there.

**Comment by Delta-99** [comment] 2021-04-18 15:54
Should we close this one @thebgpikester @funkyfranky

**Comment by thebgpikester** [comment] 2021-04-18 17:32
ultimatley not reproducible and since then not much appetite to continue looking.

**Closed by thebgpikester** 2021-04-18 17:32 UTC
Labels: DCS bug, Workaround
