### ISSUE TITLE
SPAWN: Planes spawning on top of each other in AI_BALANCER

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#803] opened 2018-02-05 23:17 UTC
This probably isn't specific to AI_BALANCER but anywhere that planes are spawning at airfields where the same template is being used perhaps?

This seems to be a bug introduced in DCS 2.5 as far as I can tell. Some others saying probably 2.2 because they were seeing it on NTTR in 2.2.

If you load up the demo mission AIB-007 you can see this happening at Sochi-Adler and Batumi whereas at the rest of the airbases things seem to work fine. Why is that you ask? Well, at Sohci and Batumi there is more than one CLIENT plane defined. So if there are no players taking those spots, then at those airbases more than 1 AI plane will be spawned to replace the CLIENT planes. This is where they spawn on top of each other in DCS 2.5. In 1.5.8 they would pick different parking spots.

This only seems to be an issue when **COLD** start is selected on the AI template being used. If you switch to **HOT** start then the first one will spawn, start taxing almost immediately and the 2nd one will spawn as soon as the parking spot is free (**see update below - it helps but not fully**)

There might be a work-around that we can apply in Moose to force a different parking spot or something. Not sure. Or we report it to ED and hopefully they fix it by 2020.

**UPDATE: The HOT start helped a little bit in some cases but not completely. I think it is just luck of the draw but I still occasionally got more than 1 spawning on top of each other**

**Comment by Delta-99** [comment] 2018-02-09 04:34
UPDATE: Another thing that helped was to redefine the parking spots by going into the ME and selecting every single flight, changing the parking spot and then changing it again. I think between 1.5.8 and 2.5 the parking positions are messed up in the editor and need to be re-assigned.

NOW, this didn't 100% fix the problem but it severely reduced the issue as far as I can tell.

**Comment by FlightControl-User** [comment] 2018-02-18 10:38
ohh ohhh! This is a severe bug.

**Comment by FlightControl-User** [comment] 2018-03-03 06:05
@funkyfranky @Delta-99 I've been following this up from your conversations on discord. Can you please update your findings here? Or it will get lost. I am going through the (huge) list of changes and issues and I won't have time for this right now. I hope next week. But please update with the latest info or it will all get lost within discord somewhere.

**Comment by Delta-99** [comment] 2018-03-03 18:36
No worries just load up AIB-007 and you will see the problem. Might be any older AIB mission. My comments above should be pretty accurate as to what I saw. Discussion on Discord won’t add much to this.

**Comment by FlightControl-User** [comment] 2018-03-03 19:18
Ok!

**Comment by funkyfranky** [comment] 2018-03-03 20:14
All my findings are here https://forums.eagle.ru/showpost.php?p=3413307&postcount=8

**Comment by Delta-99** [comment] 2018-07-01 02:12
So this latest DCS version that I just tried (I have not touched my mission or touched Moose) and things seem to be spawning WAY better (potentially resolved). I haven't tried the DEMO AIB mission yet but if tried and things are working then this was a bug DCS introduced for a number of versions now!! DCS version 2.5.2.18736 is the one I just tested which seems to be working way better!!

**Comment by thebgpikester** [comment] 2018-07-01 08:58
Ran it a fair few hours using the same core code but in A2A_Dispatcher and not noticed spawning on Runway or not spawning at all and I consider it the same, that this is fixed on the Dev branch.

Closing as "fixed in Dev branch" for now, can review later if it recurs.

**Comment by thebgpikester** [comment] 2018-07-01 19:34
Frank stated that the spawn at airbase function is shared by both. I used A2A_Dispatcher to test. It's not easy to reproduce in the first place, but the spawn method logic you can watch through the new logging and parking spaces are searched, and when it couldnt find one it resorted to spawning InAir rather than having a hiccup. We found a last bug with that due to multiple units in group, but the evidence of the fix was pretty strong. You are welcome to test SpawnAtAirbase() via any of the modules or directly.

**Comment by Delta-99** [comment] 2018-07-01 21:20
Tested this again just now using AIB 007 as reported in the initial issue. Same issue is happening. I tested using an old version and latest version of Moose from develop.

Same issue which only seems to appear at SOCHI and BATUMI. If you watch the logs you can see this is the only place that a RespawnFunction(Respawn) is being called. Likely when it is trying to cleanup planes and respawn.

Note, one cannot see planes spawning on top of each other anymore unless they are exactly on top of each other and you can see more that 2 models. But you can see them spawn and just sit there. If you watch long enough they will disappear and another spawned. Then they don't move either.

**Comment by thebgpikester** [comment] 2018-07-01 21:37
OK Spawn, I expected, wasn't aware AIB used both or not SpawnAtAirbase().
It would be nice to get this into spawn but I'm not sure it works with templates :/

**Comment by funkyfranky** [comment] 2018-07-01 21:39
I guess there is another function than SpawnAtAirbase() called. So the new logic is probably not applied in these cases.
For example there is GROUP:Repawn() and GROUP:RespawnAtAirbase(). In particular the latter should be updated with the new logic.

**Comment by FlightControl-User** [comment] 2018-10-01 18:34
Is this still valid?

**Comment by thebgpikester** [comment] 2020-02-08 17:12
I think this might still be valid actually O.o

**Comment by baluballa** [comment] 2020-02-14 13:20
Updating Moose.lua to latest from developer branch solves issue with AI_BALANCER, spawn bug in AIB-007. Also have tested other missions with same symptoms. See issue #1245 ...

**Comment by thebgpikester** [comment] 2020-02-18 16:32
i strongly think this is worth testing on 2.5.6 actually. I know ED still work on avoiding collisions and made changes to prevent parking specifics in some cases, like on ships, so the new 2.5.6 version will have changed code and it's just worth a quick test to ensure it still works, IMHO.

**Comment by thebgpikester** [comment] 2020-02-23 01:20
worked fine just now. Closing.

**Closed by thebgpikester** 2020-02-23 01:20 UTC
Labels: Tested, fixed

**Comment by 1noob4ever** [comment] 2020-09-22 14:14
This seems to still be an issue with AI_Balancer, specifically AIB007. Any base that has more than one client then it will attempt to spawn multiple non client aircraft on top of one another then explode. Rinse repeat. I want to note also that the other night I was flying a multiplayer i'm pretty sure the author was using MOOSE and i noticed that ground units were spawning on top of each other. Pretty weird at first when i saw a hybrid Shilka_T-80 tank. This was repeated in all of the little platoon size groups.
