### ISSUE TITLE
SCORING: Score based on time, score is not registrated with _AddMissionScore funciton

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#212] opened 2017-01-23 13:23 UTC
Log output.

04543.185 INFO    SCRIPTING:  17533(   112)/E:             SCORING00000._AddMissionScore({[1]={["MissionReportShow"]=false,["MissionBriefing"]="Enemy tank platoons is approaching the Senaki-Kolki, defend it at all cost. In case of overtake, use nearby AB Kutais or Heli FARP at GG69 for supplies",["MissionProgressTrigger"]=0,["MissionStatus"]="PENDING",["FAILED"]=2,["MissionPriority"]="Very High",["Name"]="Defend Senaki-Kolki",["_ActiveTasks"]={},["CommandCenter"]={["Missions"]={[table: 0000000090DB1D20]=,},["CommandCenterPositionable"]={["ClassName"]="GROUP",["GroupName"]="HQ",},["CommandCenterName"]="Papa",["ClassName"]="COMMANDCENTER",["CommandCenterMenu"]={["Menus"]={[table: 000000008E08FB00]={["Menus"]={[table: 000000002D7330F0]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Abort Task",["MenuText"]="Abort Task",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Abort Task",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]={["ClassName"]="GROUP",["GroupName"]="Commander",["_Menus"]={["Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop Orange smoke on targets"]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop Orange smoke on targets",["MenuText"]="Drop Orange smoke on targets",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",[4]="Drop Orange smoke on targets",},["ParentMenu"]={["Menus"]={[table: 000000009327E0A0]=,[table: 0000000051D14D70]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop green smoke on targets",["MenuText"]="Drop green smoke on targets",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",[4]="Drop green smoke on targets",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},[table: 00000000B8748DC0]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop blue smoke on targets",["MenuText"]="Drop blue smoke on targets",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",[4]="Drop blue smoke on targets",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},[table: 00000000BE11A160]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop Red smoke on targets",["MenuText"]="Drop Red smoke on targets",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",[4]="Drop Red smoke on targets",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},[table: 0000000091FC4D70]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop White smoke on targets",["MenuText"]="Drop White smoke on targets",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",[4]="Drop White smoke on targets",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},},["MenuText"]="Target acquisition",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Target acquisition",},["ParentMenu"]=,["MenuGroup"]=,["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Target acquisition",["ClassName"]="MENU_GROUP",["MenuGroupID"]=39,},["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},["Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop blue smoke on targets"]=,["Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop green smoke on targets"]=,["Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop White smoke on targets"]=,["Command Center (Papa)@Defend Senaki-Kolki@Target acquisition@Drop Red smoke on targets"]=,["Command Center (Papa)@Defend Senaki-Kolki@Task Status"]={["Path"]="Command Center (Papa)@Defend Senaki-Kolki@Task Status",["MenuText"]="Task Status",["MenuPath"]={[1]="Command Center (Papa)",[2]="Defend Senaki-Kolki",[3]="Task Status",},["ParentMenu"]=,["ClassName"]="MENU_GROUP_COMMAND",["MenuGroupID"]=39,["MenuGroup"]=,},["Command Center (
04543.186 INFO    SCRIPTING:  17534(   112)/E:             SCORING00000._AddMissionScore({["TAW_Wingthor"]={["Kill"]={[2]={["GAZ-3308"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["SKP-11"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["BTR_D"]={["PenaltyKill"]=0,["ScoreKill"]=7,["Score"]=70,["Penalty"]=0,},["Ural-375 PBU"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["Ural-375 ZU-23"]={["PenaltyKill"]=0,["ScoreKill"]=2,["Score"]=20,["Penalty"]=0,},["GAZ-3307"]={["PenaltyKill"]=0,["ScoreKill"]=2,["Score"]=20,["Penalty"]=0,},},},["HitUnits"]={},["PenaltyCoalition"]=0,["UnitCoalition"]=2,["HitPlayers"]={},["PenaltyWarning"]=0,["UnitCategory"]=0,["UnitType"]="Su-25T",["Hit"]={[2]={["Spawn1#001-14"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Unit #087"]={["ScoreHit"]=0,["Penalty"]=20,["Score"]=0,["PenaltyHit"]=2,},["Spawn1#001-13"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-07"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-05"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-02"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-06"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-03"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-15"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-08"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-01"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-11"]={["ScoreHit"]=3,["Penalty"]=0,["Score"]=3,["PenaltyHit"]=0,},["Spawn1#001-12"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-09"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-04"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},},},["UnitName"]="Pilot #016",["Penalty"]=20,["Score"]=162,["Mission"]={},},})
04543.187 INFO    SCRIPTING:  17538(   112)/E:             SCORING00000._AddMissionScore({["Kill"]={[2]={["GAZ-3308"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["SKP-11"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["BTR_D"]={["PenaltyKill"]=0,["ScoreKill"]=7,["Score"]=70,["Penalty"]=0,},["Ural-375 PBU"]={["PenaltyKill"]=0,["ScoreKill"]=1,["Score"]=10,["Penalty"]=0,},["Ural-375 ZU-23"]={["PenaltyKill"]=0,["ScoreKill"]=2,["Score"]=20,["Penalty"]=0,},["GAZ-3307"]={["PenaltyKill"]=0,["ScoreKill"]=2,["Score"]=20,["Penalty"]=0,},},},["HitUnits"]={},["PenaltyCoalition"]=0,["UnitCoalition"]=2,["HitPlayers"]={},["PenaltyWarning"]=0,["UnitCategory"]=0,["UnitType"]="Su-25T",["Hit"]={[2]={["Spawn1#001-14"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Unit #087"]={["ScoreHit"]=0,["Penalty"]=20,["Score"]=0,["PenaltyHit"]=2,},["Spawn1#001-13"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-07"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-05"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-02"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-06"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-03"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-15"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-08"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-01"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-11"]={["ScoreHit"]=3,["Penalty"]=0,["Score"]=3,["PenaltyHit"]=0,},["Spawn1#001-12"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},["Spawn1#001-09"]={["ScoreHit"]=1,["Penalty"]=0,["Score"]=1,["PenaltyHit"]=0,},["Spawn1#001-04"]={["ScoreHit"]=2,["Penalty"]=0,["Score"]=2,["PenaltyHit"]=0,},},},["UnitName"]="Pilot #016",["Penalty"]=20,["Score"]=162,["Mission"]={},})
04543.187 INFO    SCRIPTING:    112(  8076)/E:                BASE00000.IteratorFunction({[1]="Inisde the scoring function",})

**Comment by FlightControl-Master** [comment] 2017-02-24 11:27
heum ... it is a bit hard for me to follow this. You mean, that when you call the function, the score is not added for the player?

**Comment by FlightControl-Master** [comment] 2017-03-05 05:56
@baluballa Please provide feedback or this issue. What is the goal of this? I can't follow the question.

**Comment by Grey-Echo** [comment] 2017-03-25 21:15
I don't want to sound rude, but he posted that 2 month ago. I'm going to go ahead and close this issue. @baluballa , if the issue is still relevant, please create a new one !

**Closed by Grey-Echo** 2017-03-25 21:15 UTC
Labels: question
