### ISSUE TITLE
AI Cargo Dispatcher will not accept Group Zone for the Deployment zone

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#943] opened 2018-06-30 23:24 UTC
Following code will cause error
local AdvancedMarineRecon = GROUP:FindByName("FO Marine Landing Group")
local AdvancedMarineReconZone = ZONE_GROUP:New("Advanced Marine Recon", AdvancedMarineRecon, Radius)

local Setbeachzone = SET_ZONE:New(AdvancedMarineReconZone)
      local SetCargopltabk = SET_CARGO:New():FilterTypes( "abk" ):FilterStart()
      local Setabtrk = SET_GROUP:New():FilterPrefixes( "FO ABTrk" ):FilterStart()
      AICargoDispatcherplabk = AI_CARGO_DISPATCHER_APC:New( Setabtrk, SetCargopltabk, Setbeachzone , 1000 ) 

Error message:

2018-06-30 23:15:40.334 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:75957: attempt to index local 'DeployZone' (a nil value)
2018-06-30 23:15:40.334 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19570: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19566>
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:75957: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:75953>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19578: in function '_call_handler'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19675: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19584>
	(tail call): ?
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:75801: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:75800>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19914: in function '_call_handler'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19675: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:19584>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:5009: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS.openbeta\/~mis0000461E"]:4968>

SET_ZONE wont accept group zones or polygon zones... Needs to be able to do this.

**Comment by thebgpikester** [comment] 2018-07-04 12:18
Poly Zones aren't  implemented for several modules. This is a feature request not a bug as far as I can see for your report, please clarify if this is factually incorrect.

**Comment by gunterlund** [comment] 2018-07-04 13:48
IF it doesnt exist today then I guess it would be a feature. Would like to expand what is considered a deployment zone other than what is created in SET_Zone.

**Comment by thebgpikester** [comment] 2020-02-13 16:38
I suggest either closing or committing to the work, needs to be reassessed for effort, but Frank, you did self assign, so let me know.

**Comment by funkyfranky** [comment] 2020-10-26 08:07
This looks more like a user error as `local Setbeachzone = SET_ZONE:New(AdvancedMarineReconZone)` this does not add the AdvancedMarineReconZone to the set of zones.

**Closed by funkyfranky** 2020-10-26 08:07 UTC
Labels: Additional Data Requested, Enhancement
