### ISSUE TITLE
AI_Carg_Dispatcher_Helo

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#908] opened 2018-05-27 18:49 UTC
Cargo errors out randomly after leaving cargo. Will not proceed to zone. Also when error occurs, carrier will not leave deployment zone and is stuck

**Comment by gunterlund** [comment] 2018-05-27 18:50
[dcs (1).log](https://github.com/FlightControl-Master/MOOSE/files/2042901/dcs.1.log)

log showing error after using mission 240

**Comment by gunterlund** [comment] 2018-05-27 18:52
copy of mission that dropped is located in discussion thread on discord

**Comment by FlightControl-User** [comment] 2018-05-27 19:07
Thank you Bryce

**Comment by FlightControl-User** [comment] 2018-05-28 04:50
Fixed in 2.4.a. You can retest. 

Root cause: I had put in limits on height and speed when i allow units to board into helos.
but there was an error in the height calculation and the speed treshold was set to 5 kmp/h
and the helo that landed at 5.025447373 kmp/h
so it didn't board ....
but now i moved that treshold up to 7 kmph

**Comment by gunterlund** [comment] 2018-05-28 15:30
still erroring out. See comments in discord. I think errors may be tied to movement of ground troops after landing. Not all groups got picked up.

**Comment by FlightControl-User** [comment] 2018-05-28 15:31
Is this after modifications to the mission?

**Comment by Delta-99** [comment] 2018-05-28 21:20
Its actually worse for me with changes from today.

`2018-05-28 20:30:06.087 INFO    SCRIPTING: *** MOOSE GITHUB Commit Hash ID: 2018-05-28T15:13:29.0000000Z-6149e741d160f64603023c1a6ba999e365632ab4 ***
`
Looks like the pickup is working pretty good but I wasn't looking at that as much.

But the drop-off even worse than before. Before at least at some point the helo's would eventually land maybe after 5 mins of dancing around. But now, at some point they get to a situation where they just dance around forever and never land. This ended up tying up the entire process.

I have a video and log file. Just need to figure out where to attach or post them.

I will make my comments about the video per time period:

00:40 - Pickup is decent even with multiple transports near the same area.
01:40 - 4 transports heading to the same drop off area. Initially this was looking pretty good. The first 2 look to have landed pretty decently. I thought things were fixed. BUT then things go crappy. First 2 land perfectly, other 2 start their dance. I think the 3rd finally gets its cargo unloaded but the 4th just keeps dancing forever.
05:31: This transport on the far right I think is the only one that went to that location. Never landed and just did his dance the entire time.
06:22: 4 tranports at the far left dancing, never landing. 2 at the far right dancing and never landing.

**Comment by FlightControl-User** [comment] 2018-06-03 05:12
@Delta-99 the towers are in the way. move the towers outside of the landing zone.

**Comment by Delta-99** [comment] 2018-06-04 01:33
Ok, this works much much better for unloading. It was the damn towers. I wonder if any sort of static like that will cause the issue. But its not a big deal and likely not much we want or can do about it anyway. Will just have to make sure the landing zones are pretty clear.

They do seem to take longer to land I THINK for deploying compared to when picking up but I have to look at that closer. I wasn't keeping a good eye on that but rather whether the landing was actually working decently.

However, I'm not sure if it is this issue or if there is another issue for this but I am seeing the same thing @gunterlund is seeing as described on Discord. That is not all the ground troops are picked up. I have about 12 ground groups or more and about 6 heli's so they have to make multiple trips. For whatever reason only a very small number of them seem to make a 2nd trip. The rest just go to the home landing spot leaving a bunch of infantry stranded in the end.

**Comment by FlightControl-User** [comment] 2018-09-29 13:45
Please confirm if this is fixed. Closing this.

**Closed by FlightControl-User** 2018-09-29 13:45 UTC
Labels: bug, ready for testing
