### ISSUE TITLE
Troops disembark show positive and penalty of score.

### ISSUE THREAD

**Issue by APEXDCS** [FlightControl-Master/MOOSE#1143] opened 2019-04-09 21:40 UTC
When deploying troops, there is a penalty on the scoring system as troops appear to be destroyed and respawned with CARGO.

**Comment by thebgpikester** [comment] 2020-02-08 15:09
is this still unresolved?
It's the SCORING class where the issues is right?

**Comment by baluballa** [comment] 2020-02-13 09:14
@APEXDCS can you plz confirm if this issue still applies.

**Comment by thebgpikester** [comment] 2020-02-13 16:33
Millertime says it does. It appears for some reason the player is attributed a negative score despite not shooting the cargo. That doesnt really make sense. Will need that mission, Ive used scoring and destroyed things manually and not had spurious scores so we will need more to reproduce.
If this is an issue, please help us out with a miz to reproduce, because without Sven it will be painful.

**Comment by thebgpikester** [comment] 2020-02-13 16:50
Closing. If we hear more about it and it has wider connotations we can reopen to look at Scoring. I think Scoring has other general issues of accuracy all over it that really need it to be reviewed in entirety if we will have it as more useable

**Closed by thebgpikester** 2020-02-13 16:50 UTC
Labels: Additional Data requested, question
