### ISSUE TITLE
TASK_BAI error on report successful tasks

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#820] opened 2018-03-06 20:58 UTC
Playing with the menus on task. Tried to list successful tasks in a mission and got this error:

```
2018-03-06 20:52:13.212 INFO    SCRIPTING:   5820(    13)/E:               EVENT00000.onEvent({[1]=S_EVENT_DEAD,[2]={[IniUnit]={[SceneryObject]={[id_]=77271722,},[ClassName]=SCENERY,[SceneryName]=77271722,},[initiator]=,[id]=8,[IniObjectCategory]=5,[IniUnitName]=77271722,[IniCategory]=4,[time]=28912.801,[IniTypeName]=SCENERY,[IniDCSUnit]=,[IniDCSUnitName]=77271722,},[3]=77271722,[5]=-1,})
2018-03-06 20:52:19.606 INFO    SCRIPTING:  61365(    -1)/E:        TASK_A2G_BAI00170.function({[1]=<-> Task Replanned,[TaskName]=Bridge,[Mission]=Mission "Mother (Primary)",})
2018-03-06 20:52:19.606 INFO    SCRIPTING:  61366(    -1)/E:        TASK_A2G_BAI00170.function({[1]=<-> Task Player Names,[PlayerNames]={[New callsign]={[ClassName]=GROUP,[GroupName]=client 2,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},},},})
2018-03-06 20:52:19.620 INFO    SCRIPTING:  61115( 60718)/E:        TASK_A2G_BAI00170.RemoveStateMachine(Garbage Collected, Processes should be finalized now ...)
2018-03-06 20:52:19.623 INFO    SCRIPTING:   7984( 60952)/E:                BASE00000.Remove({[1]=Cannot Remove MENU_GROUP_DELAYED,[Group]={[ClassName]=GROUP,[GroupName]=client 2,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},},[Path]=@Command Center (Mother)@Mission "Mother (Primary)"@Join Planned Task,[MenuText]=Join Planned Task,[ParentMenu]={[Menus]={[Assigned Task Bridge]={[MenuTag]=Tasking,[Group]=,[MenuSet]=true,[ClassName]=MENU_GROUP_DELAYED,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Assigned Task Bridge,},[GroupID]=6,},[Task Reports]={[Menus]={[Report Assigned Tasks]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Assigned Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]={[MissionBriefing]=Phase1,[MissionStatus]=PENDING,[AssignedGroups]={},[MissionPriority]=Primary,[Name]=Mother,[MissionMenu]=,[Tasks]={[Factory]={[GoalTotal]=1,[current]=Success,[MenuPlanned]={},[TaskBriefing]=Destroy the Factory at somewhere,[MenuAssigned]={},[ClassName]=TASK_A2G_BAI,},[Bridge]={[GoalTotal]=1,[current]=Success,[MenuPlanned]={[table: 000000007ED9EA80]={[MenuTag]=Tasking,[Group]=,[MenuSet]=true,[ClassName]=MENU_GROUP_DELAYED,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Join Planned Task,},[GroupID]=6,},},[TaskBriefing]=Destroy the Bridge at somewhere,[MenuAssigned]={[table: 000000007ED9EA80]=,},[ClassName]=TASK_A2G_BAI,},},[CommandCenter]={[Missions]={[table: 000000008A9B6C90]=,},[CommandCenterCoalition]=2,[ReferenceNames]={},[CommandCenterPositionable]={[ClassName]=GROUP,[GroupName]=Mother,[Takeoff]={[Air]=1,[Hot]=3,[Runway]=2,[Cold]=4,},},[ReferencePoints]={},[CommandCenterName]=Mother,[ClassName]=COMMANDCENTER,[Name]=,[CommunicationMode]=80,},[_StartState]=IDLE,[ClassName]=MISSION,[current]=ENGAGED,[MissionGroupMenu]={[table: 000000007ED9EA80]={[ReportMissionHistory]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Statistics Reports,[4]=Report Mission Progress,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[n]=2,},[GroupID]=6,},[MarkTasks]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Mark Task Locations on Map,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[n]=2,},[GroupID]=6,},[TaskReportsMenu]=,[ReportSuccessTasksMenu]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Successful Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[3]=Success,[n]=3,},[GroupID]=6,},[PlayerReportsMenu]={[Menus]={[Report Mission Progress]=,[Report Players per Task]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Statistics Reports,[4]=Report Players per Task,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[n]=2,},[GroupID]=6,},},[Group]=,[ClassName]=MENU_GROUP,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Statistics Reports,},[GroupID]=6,},[ReportHeldTasksMenu]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Held Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[3]=Hold,[n]=3,},[GroupID]=6,},[ReportPlannedTasksMenu]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Planned Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[3]=Planned,[n]=3,},[GroupID]=6,},[ReportFailedTasksMenu]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Failed Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[3]=Failed,[n]=3,},[```
GroupID]=6,},[ReportPlayersPerTaskMenu]=,[ReportAssignedTasksMenu]=,[ReportTasksMenu]={[Group]=,[MenuPath]={[1]=Command Center (Mother),[2]=Mission "Mother (Primary)",[3]=Task Reports,[4]=Report Tasks,},[ClassName]=MENU_GROUP_COMMAND,[CommandMenuArguments]={[1]=,[2]=,[n]=2,},[GroupID]=
2018-03-06 20:52:57.777 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "D:\temp\DCS.openbeta\/~mis00007C37"]:62934: attempt to call method 'GetData' (a nil value)
2018-03-06 20:52:57.777 INFO    SCRIPTING: stack traceback:
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:7135: in function 'GetData'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:62934: in function 'ReportOrder'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:59999: in function <[string "D:\temp\DCS.openbeta\/~mis00007C37"]:59999>
	(tail call): ?
	[C]: in function 'sort'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:2895: in function 'spairs'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:59999: in function 'ReportOverview'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:60092: in function <[string "D:\temp\DCS.openbeta\/~mis00007C37"]:60090>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\temp\DCS.openbeta\/~mis00007C37"]:7146: in function <[string "D:\temp\DCS.openbeta\/~mis00007C37"]:7142>
2018-03-06 20:53:24.251 INFO    SCRIPTING:   5820(    13)/E:               EVENT00000.onEvent({[1]=S_EVENT_MISSION_END,[2]={[id]=12,[time]=28983.764,},[5]=1,})

```
I have managed to do this a few ways but getting a repeatable order is tricky and takes time. SO this isn;t a great report, sorry. willing to work with you on it though.

**Comment by FlightControl-User** [comment] 2018-03-06 21:16
So this is on completed tasks?

**Comment by thebgpikester** [comment] 2018-03-06 21:23
it hit after I completed two tasks in a mission and went back into the mission menu to have a look at the reports. Since i'm still playing with quite complex usage that there are no examples for my code is changing a lot tonight. What I wanted to see is if the MISSION completed by itself and did anythign to the menu.

**Comment by FlightControl-User** [comment] 2018-03-06 21:26
So, completed tasks is the problem. I think you're doin some great tests there! Exactly what is needed!

**Comment by thebgpikester** [comment] 2018-03-06 21:30
Live report, I notice when completing a TASK in that mission, you remain in that task and assigned. the BR still keeps going towards it.
Note that I'm being unusual in my objectives are not standard units I've got static units, I assigned them manually to the set and yes, it work very well and i'm super happy. But there's a general restriction that TASKS need something to die. I'd like it so that wasn;t the case so I can use scenery but overlay a unit or tiny unkillable static over the top so I can direct players then call the TASK:Success() manually and eventually feed into MISSION:Complete()

**Comment by thebgpikester** [comment] 2018-03-06 21:38
OK, I think i'm at the stage where I can better define the problem and give you a mission and code. In this scenario I have 1 mission, two tasks. Each task has a defined unit of a static object. There are no errors in the logs and the script runs fine and you can join either tasks from the MISSION. It then provides you updates as expected including the Task success. You can report on that too but you get stuck in the Task and cannot escape to assign yourself to the next task. The successful task also does NOT disappear from available tasks and keeps spitting out the BR at you and nothing you cna do can get you onto another task.

So, I would expect the task on success to drop from available tasks, allow you to select a new one. And this is what happens. The error above I didn't get. Also mind if this needs normal units, it's not explicitly said as such.

Supplied mission for testing. There are 2 triggers you can use to blow up the task targets so you can test simply sitting still. Will update and upload this shortly.

**Comment by thebgpikester** [comment] 2018-03-06 21:44
[missiontasktestingbug.zip](https://github.com/FlightControl-Master/MOOSE/files/1786853/missiontasktestingbug.zip)

```
HQ = GROUP:FindByName( "Mother", "Ship" )
CommandCenter = COMMANDCENTER:New( HQ, "Mother" )
Scoring = SCORING:New( "BAI Demo" )
Mission = MISSION
  :New( CommandCenter, "Mother", "Primary", "Phase1", coalition.side.BLUE, "Destroy various targets for phase1" )
  :AddScoring( Scoring )
MyStatic1 = STATIC:FindByName("tgt2")
MyStatic2 = STATIC:FindByName("tgt1")
AttackGroups = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "client" ):FilterStart()
TargetSetUnit1 = SET_UNIT:New()--:FilterCoalitions("red"):FilterStart()
TargetSetUnit2 = SET_UNIT:New()
TargetSetUnit1:AddObject(MyStatic1)
TargetSetUnit2:AddObject(MyStatic2)
TaskBAI = TASK_A2G_BAI:New( Mission, AttackGroups,"Factory", TargetSetUnit1, "Destroy the Factory at somewhere" )
TaskBAI2 = TASK_A2G_BAI:New( Mission, AttackGroups,"Bridge", TargetSetUnit2, "Destroy the Bridge at somewhere" )


EventHandler = EVENTHANDLER:New()
EventHandler:HandleEvent( EVENTS.Dead )
function EventHandler:OnEventDead( EventData )
if EventData.IniUnitName == 77271722 then 
  MESSAGE:New("Dzhvari Dam bridge destroyed",10):ToAll()
  flag1 = 1
end
end

function TaskBAI:onenterSuccess(Event, From, To)
Mission:GetCommandCenter():MessageToCoalition( "Bridge damaged enough" )
TaskBAI:Success()
Task1=1
end


function TaskBAI:onenterSuccess(Event, From, To)
Mission:GetCommandCenter():MessageToCoalition( "Factory destroyed!" )
TaskBAI2:Success()
Task2=1
end


function Mission:OnAfterMissionGoals( From, Event, To )
if Task1==1 and Task2==1 then
Mission:GetCommandCenter():MessageToCoalition( "All targets destroyed!" )
Mission:Complete()
end
end
```

**Comment by FlightControl-User** [comment] 2018-03-09 09:31
So, it is a bug (my fault).
When a task is planned, then that task comes with "task info".
like coordinates, target info, etc.
while the task is planned, however, at each detection scan, the task info is "updated", (refreshed).
because targets move, can change composition etc (it is a looong story)
now ...
when a task is assigned to a player, that refreshing stops. the task info is "frozen"
when the task is completed, the reports should still how the task info of the initial planned task (some info).
so, what the mistake is
i forgot to manage that last bit, the persistent copy of the task info from the planned stage, so what task info can be shown when completed.
and that generates the errors
it used to work before, it was implemented before
but i've reworked the whole task info logic (made it much more structured) but forgot to reprogram that last bit
i'll work on that now
and i hope that then the tasking comes back together as it was.

**Comment by FlightControl-User** [comment] 2018-03-09 11:39
I think this can be retested.

**Comment by thebgpikester** [comment] 2018-03-09 11:54
Already?! 
Will do so this evening.

**Comment by Delta-99** [comment] 2018-03-18 20:36
@thebgpikester did you confirm if this is fixed?

**Comment by fastfiveoh** [comment] 2018-03-19 03:40
I have tested the situation @thebgpikester posted with his mission.  He is indeed correct, you are unable to complete the task.    When you assign yourself to the task, complete it via the menu explode option or by actually flying the mission, you get the notification that the item was destroyed, and if you do an update on the task status it says its complete.  Your only option is to Abort the mission to clear it. 

Assigning the mission 
![image](https://user-images.githubusercontent.com/23316694/37576822-7b8f1ea4-2aeb-11e8-9a15-bff56b694dcc.png)

First portion destroyed, still receiving BR calls
![image](https://user-images.githubusercontent.com/23316694/37576890-e45e5cb0-2aeb-11e8-9a54-5792a9433eb9.png)

Menu options after factory is confirmed destroyed

![image](https://user-images.githubusercontent.com/23316694/37576917-0c8444a2-2aec-11e8-9236-ca85f8c397d0.png)

Task status, still getting BR calls
![image](https://user-images.githubusercontent.com/23316694/37576941-3472a1b6-2aec-11e8-99e1-cebb9352a900.png)

Trying to join second task options (plus BR calls for first task)

![image](https://user-images.githubusercontent.com/23316694/37576963-595e3ca6-2aec-11e8-95c4-34d603750e33.png)

Task that was still successful still available as an option
![image](https://user-images.githubusercontent.com/23316694/37577000-9101af26-2aec-11e8-9452-a8ee04c13173.png)

My opinion.  I tested this with @thebgpikester mission and then my own mission.  The difference is that his are static objects and mine are units.  This seems to be related potentially the type of unit used.

**Comment by FlightControl-User** [comment] 2018-03-27 13:45
What is the status of this one?

**Comment by FlightControl-User** [comment] 2018-03-27 13:56
This got fixed. Now i know what this was about. Fixed and can be closed.

**Closed by FlightControl-User** 2018-03-27 13:56 UTC
Labels: Tested, bug, fixed, ready for testing
