### ISSUE TITLE
SET: Error when leaving units, PLAYER LEAVE event crashes.

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#368] opened 2017-03-29 13:20 UTC
In my log it looks like Im getting errors when I enter and or leave units in a mission. At this area

```lua
--- Handles the OnPlayerLeaveUnit event to clean the active players table.
-- @param #SET_BASE self
-- @param Core.Event#EVENTDATA Event
function SET_BASE:_EventOnPlayerLeaveUnit( Event )
  self:F3( { Event } )
  local ObjectName = Event.IniDCSUnit
  if Event.IniDCSUnit then
    if Event.IniDCSGroup then
      local GroupUnits = Event.IniDCSGroup:getUnits()
      local PlayerCount = 0
      for _, DCSUnit in pairs( GroupUnits ) do
        if DCSUnit ~= Event.IniDCSUnit then
          if DCSUnit:getPlayer() ~= nil then
            PlayerCount = PlayerCount + 1
          end
        end
      end
      self:E(PlayerCount)
      if PlayerCount == 0 then
        self:Remove( Event.IniDCSGroupName )
      end
    end
  end
end
```
Creates this error:
```
00283.033 INFO    SCRIPTING:   5075(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001320",[3]=2,})
00283.033 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
00283.033 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

**Comment by FlightControl-Master** [comment] 2017-03-29 14:11
Multi or single player?

**Comment by FlightControl-Master** [comment] 2017-03-29 14:13
How many clients in the group? More than one?

**Comment by FlightControl-Master** [comment] 2017-03-29 14:13
If more than one => DCS BUG

**Comment by gunterlund** [comment] 2017-03-29 14:58
Single player

**Comment by FlightControl-Master** [comment] 2017-03-29 15:25
CA units .. Ok ... Ill test.

**Comment by FlightControl-Master** [comment] 2017-03-31 09:42
I have tested this, and just cannot simulate this... 

`if DCSUnit:getPlayer() ~= nil then`

It is the above line that is causing the crash, with the following error:

```
00283.033 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
00283.033 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

Can you try to reproduce the error and explain exactly WHEN the error happens?
What are your actions you do in detail please? I have been switching from one unit to another, going to spectators, going back etc. I just cannot get this simulated.

FC

**Comment by Grey-Echo** [comment] 2017-03-31 10:14
If `DCSUnit` is actually a DCS Unit, then this error makes a whole lot of sense. There is no such thing as `Unit:getPlayer()`. Did you mean `DCSUnit:getPlayerName()` instead ? 
http://wiki.hoggit.us/view/DCS_func_getPlayerName

**Comment by gunterlund** [comment] 2017-03-31 15:18
That is from my log. I'm not creating that

**Comment by FlightControl-Master** [comment] 2017-03-31 16:53
@gunterlund. I an having trouble to reproduce this. Can you please elaborate when this happens... Immediately? After one hour? When you leave a ground unit and jump into another? Etc?

**Comment by gunterlund** [comment] 2017-03-31 17:34
https://flightcontrol.slack.com/files/gunterlund/F4R3VH8CT/dcs.log

**Comment by Grey-Echo** [comment] 2017-03-31 19:17
Yeah, sorry, I wasn't clear enough. What I meant is : In Moose, Core.Set, line 468, is
`if DCSUnit:getPlayer() ~= nil then`. So, @FlightControl-Master ,Did you mean `DCSUnit:getPlayerName()` instead ?

**Comment by FlightControl-Master** [comment] 2017-04-01 18:55
Sorry @gunterlund but with the help of @Delta-99 i could fix this issue. I had overlooked SET_BASE....
Didn't realize you had a SET_GROUP defined!!! Of course i could not simulate. I created test mission SET-103 to test this scenario, when i had the original code, i could resimulate, when i fixed the code to "getPlayerName" it works... I still need to review this code though, not even sure it is still needed. But the bug is resolved by this.

We'll do a hotfix on release 2.0... We'll make 2.0.1...

**Comment by gunterlund** [comment] 2017-04-01 18:59
Sorry guys for bringing this up. I was worried about errors happening with a new release. I'm hear to help if I can. Don't want to be disruptive.

**Comment by FlightControl-Master** [comment] 2017-04-01 19:01
not your mistake @gunterlund . My mistake. I should have seen this ... Anyway, got the fix in master, do you run you mission from the master branch or from the master-release branch? Have you run MDES?

**Comment by gunterlund** [comment] 2017-04-02 14:10
I pull from the mission setup folder.

**Comment by Delta-99** [comment] 2017-04-02 16:26
What exactly do you mean by that @gunterlund? That you just grab the Moose.lua from setup folder? Probably isn't going to work that way anymore cause that is dynamic loading now I believe. So unless you have the new setup probably not going to work or you won't be able to test from this master without additional steps.

**Comment by gunterlund** [comment] 2017-04-02 17:12
When I get back tonight I will redo my setup. Right now I still use the original process you helped me with long ago. I have GitHub loading to my documents and I go grab moose from there.

**Comment by FlightControl-Master** [comment] 2017-04-08 07:01
@gunterlund was this tested on master?

**Comment by Grey-Echo** [comment] 2017-04-25 23:34
Since no hotfix was ever deployed, I'm assigning this to Moose 2.1, which is were it is likely going to be deployed.
I'm also closing it, since no one is complaining, it should be fixed.

**Closed by Grey-Echo** 2017-04-25 23:34 UTC
Labels: fixed, help wanted, possible bug, ready for testing

**Comment by FlightControl-Master** [comment] 2017-04-26 04:37
Yeah, this is fixed. It seems very little people check the fix after it got fixed.
