### ISSUE TITLE
SET_UNIT:New():FilterCategories("ground") throws an error if you have cargo tasks in your mission

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#974] opened 2018-08-12 02:17 UTC
Could someone have a look at this please, not just someone who wants to change labels but not actually spend the 30 seconds it takes to test and confirm it

This was tried with 
env.info( '*** MOOSE GITHUB Commit Hash ID: 2018-07-31T05:27:41.0000000Z-d5e95bb120a8eefa3fc8549c4a0e837cab0cc15d ***' )

This bug happens when you have a cargo task in your mission and try to use 
SET_UNIT:FilterCategories(Categories)
eg
local gnd_units = SET_UNIT:New():FilterCategories("ground"):FilterOnce()
env.info(" ground count units = " .. gnd_units:Count() )
this should debug output the count of all ground type objects in a mission

it wont it will throw an error instead

2018-08-06 22:00:30.121 INFO SCRIPTING: Error in timer function: [string "D:\games\1_Develop_Moose.lua"]:13635: attempt to index a nil value
2018-08-06 22:00:30.121 INFO SCRIPTING: stack traceback:
[string "D:\games\1_Develop_Moose.lua"]:4974: in function <[string "D:\games\1_Develop_Moose.lua"]:4971>
[string "D:\games\1_Develop_Moose.lua"]:13635: in function 'IsIncludeObject'
[string "D:\games\1_Develop_Moose.lua"]:11638: in function 'FilterOnce'

I have attached a mission that will replicate this 
[TAD-CGO-009 - Transport Test - Respawning Cargo_MOD.zip](https://github.com/FlightControl-Master/MOOSE/files/2280679/TAD-CGO-009.-.Transport.Test.-.Respawning.Cargo_MOD.zip)

**Comment by Delta-99** [comment] 2018-08-12 03:08
There is a reason labels are added as it helps other that might come in here and take a look. And helps to prioritize things.

Obviously you closed issue #971 cause it wasn't that simple was it. And someone actually tested that and couldn't reproduce things. SO there was a very good reason to ask for additional info.

Perhaps if you want someone to drop everything they are doing and look into your issue you should check your attitude at the door.

**Comment by thebgpikester** [comment] 2018-08-12 23:41
Making a triage assessment of bugs is standard practice in ticket workflow. There's a handful of people that are OK dabbling in MOOSE code directly, Frank that's writing his own modules, and Sven who is back to work. You should know that developer time gets sucked up with seemingly simple requests. Given the lack of dev time and availability, their rarity, and the complexity of the tasks and backlog of issues, it should be obvious that in order to close anything in the list it's going to be the easier ones, the ones with full data and steps to reproduce and the ones that can be easily understood. This is why they are marked for developer attention, by people that can assess them, so the developers that do the brunt of the work can focus and spend less time on data gathering and conversation. We all pitch in here with that effort, there's no implication that a bug assessment will be handled by the same person that assessed it. Unfortunately there is no guarantee it will be looked at at all, else I wouldn't have 24 open bugs dating back to March 2017.

Everyone is equal in this community and we contribute because we want it to grow so that more people contribute and it makes all our lives easier with DCS. No one is paid, or indeed expects anything more than, by contributing, they are making this place better. So, I find it odd that your particular contribution with that ticket is to call another community member, a "knob". 

You said above, _"I closed issue 971 because someone set it to Incomplete report which I understand due to me not giving enough info... but "_

And in your ticket you put, _"closing out because some knob set to to Incomplete report but could not spend the 30 seconds of time it would take to run attached test mission"_

It's quite clear why you struck out personally. You took offense to the "label" as a mark of dismissal of your own time you had invested in the problem and then focused on the person instead of the cold facts. 

You have fundamentally got it straight. No one wants to deal with the backlog of tickets. We aren't paid, we get nothing from it, most of them are dead ends or too little data or caused by some silly typo and it's a massive time sink. Jeez, if you think you have been wasting time in DCS, then you need to join a very long line of people that are equally disgruntled. But let's not call each other knobs or lash out because we have ended up a dead end with nothing to show for it. If you don't do the dishes, the kitchen ends up in a smelly mess, and likewise if you don't take care of your own community, it simply falls apart. Check out "Broken Windows" https://en.wikipedia.org/wiki/Broken_windows_theory. This, is a broken window. If it's not fixed, it will simply become one of many because it was allowed to go by without being fixed. Here's an opportunity for you to fix the window and make this a nicer place to spend our time in. What you do is your choice, I'd like to think you could do the right thing.

**Comment by Delta-99** [comment] 2018-08-13 01:46
I could / should have removed the “need more info” label but typically leave that for the person that ends up looking into the issue.

**Comment by FlightControl-User** [comment] 2018-08-23 18:39
Boy...

**Comment by FlightControl-User** [comment] 2018-08-23 18:40
What a long list of text

**Comment by FlightControl-User** [comment] 2018-08-23 18:41
Remove filtering from the statement

**Comment by FlightControl-User** [comment] 2018-08-23 18:41
Instead write this:

**Comment by FlightControl-User** [comment] 2018-08-23 18:43
local gnd_units = SET_UNIT:New():FilterCategories("ground")

gnd_units:FilterOnce()

env.info(" ground units = " .. gnd_units:Count() )

**Comment by FlightControl-User** [comment] 2018-08-23 18:44
The issue is that FilterOnce() does not return a self (the object)

**Comment by FlightControl-User** [comment] 2018-08-23 18:44
Let me know if this helped

**Comment by Delta-99** [comment] 2018-08-23 18:53
Is this a bug that should be fixed with FilterOnce() or is this by design?

**Comment by shadowze** [comment] 2018-08-23 18:58
good question, if I do exactly as I put in my org report BUT with group = it works
units it does not work, but the MOOSE doc examples are same for both

@FlightControl-User , yes indeedy this works once I use it as you indicated above, thanks dude

**Comment by FlightControl-User** [comment] 2018-08-23 18:59
Ok. This is a bug I think.  I don't think I did this mistake intentionally

**Comment by shadowze** [comment] 2018-08-23 19:01
your work arround works fine, so no rush

**Comment by shadowze** [comment] 2018-09-06 17:09
ok, so the work around is not working .... spent some time look at this, found the error
sometimes MUnit:GetDesc() is a nil sometimes, which is why it is throwing an error


    if self.Filter.Categories then
      local MUnitCategory = false
      for CategoryID, CategoryName in pairs( self.Filter.Categories ) do

		if MUnit:GetDesc() ~= nil then
			env.info(" cat is " .. MUnit:GetDesc().category )
			self:T3( { "Category:", MUnit:GetDesc().category, self.FilterMeta.Categories[CategoryName], CategoryName } )
			
			if MUnit:GetDesc().category  and self.FilterMeta.Categories[CategoryName] and self.FilterMeta.Categories[CategoryName] == MUnit:GetDesc().category then
				MUnitCategory = true
			end
		else
			env.info(" you got a NIL" )
		end	
		
      end
      MUnitInclude = MUnitInclude and MUnitCategory
    end

**Comment by Delta-99** [comment] 2018-09-06 17:49
@shadowze are you able to narrow it down to what unit? Is it a specific unit type or something? Not that it matters, just curious to know how reproducible this is. Or if it is just "random" which would not be good!!!!

**Comment by shadowze** [comment] 2018-09-06 17:54
i get NIL a shitload of times in the log (19 total) - can u give me some code to generate more debug output to narrow it down ?

2018-09-06 17:07:32.215 WARNING LOG: 8 duplicate message(s) skipped.
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 1
2018-09-06 17:07:32.215 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.215 WARNING LOG: 5 duplicate message(s) skipped.
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 1
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.215 WARNING LOG: 3 duplicate message(s) skipped.
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 3
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 3
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 3
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.215 WARNING LOG: 5 duplicate message(s) skipped.
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.215 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 WARNING LOG: 4 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 WARNING LOG: 1 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 1
2018-09-06 17:07:32.216 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.216 WARNING LOG: 1 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 WARNING LOG: 7 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 3
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 WARNING LOG: 19 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 WARNING LOG: 5 duplicate message(s) skipped.
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.216 INFO    SCRIPTING:  you got a NIL
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.216 INFO    SCRIPTING:  cat is 1
2018-09-06 17:07:32.217 WARNING LOG: 1 duplicate message(s) skipped.
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 3
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 0
2018-09-06 17:07:32.217 INFO    SCRIPTING:  cat is 2
2018-09-06 17:07:32.217 WARNING LOG: 1 duplicate message(s) skipped.
2018-09-06 17:07:32.217 INFO    SCRIPTING:  you got a NIL

small section above

**Comment by Delta-99** [comment] 2018-09-06 17:59
Probably need more of a code fragment. No idea what MUnit is in the code above. And not sure exactly what this is even attempting to do.

**Comment by shadowze** [comment] 2018-09-06 18:03
it is SET_UNIT  search thru moose static to find
SET_UNIT:IsIncludeObject( MUnit )

**Comment by Delta-99** [comment] 2018-09-06 18:09
Ok, I thought it might have been Moose code that you messed with but wasn't sure. So its likely a unit that doesn't have a category defined for it. Perhaps static fall into this.

Try throwing MUnit:Name() in somewhere for debugging. Or maybe MUnit:GetPrefix().

**Comment by shadowze** [comment] 2018-09-06 18:14
winner winner chicken dinner
it is **Infantry M4**
it doesnt know how to deal with them

**Comment by Delta-99** [comment] 2018-09-06 18:18
Oh shit, seriously? WTF. So a DCS bug? Super lame.

**Comment by shadowze** [comment] 2018-09-06 18:19
do not know if DCS bug or not @FlightControl-User   can you have a quick look at this and give us an idea if it is DCS or MOOSE please ?

**Comment by shadowze** [comment] 2018-09-06 18:26
no chance dude, that is waaaaaaaaaaaaaaaaaaaay too much to change, not just M4 but every single other ground unit

**Comment by shadowze** [comment] 2018-09-06 20:17
I just created a work around in the MOOSE code for the DCS / MOOSE bug, will use it until things get sorted properly

**Comment by FlightControl-User** [comment] 2018-09-07 00:26
@shadowze I am lost... 
First this is a complete other issue than the original. Second, are you telling me that the error you get is occurring after all the processed lines with an M4 unit? 
How much M4 were processed successfully before this error occurred. 
Can you please describe the scenario and when does this error occur. Is it in the beginning, after boarding, after 3 hours of game play,  ....

**Comment by FlightControl-User** [comment] 2018-09-07 01:33
Are these NIL values related to CARGO items?

**Comment by FlightControl-User** [comment] 2018-09-07 01:35
Try to add the variable MUnit.UnitName in that trace output.  Let's see what names this is occurring on.

**Comment by shadowze** [comment] 2018-09-07 08:41
1. NO Infaantry M4 units can be processed correctly it errors at the first unit and every one after that
2. how it happens = easy to repo 
local gnd_units = SET_UNIT:New():FilterCategories("ground")
gnd_units:FilterOnce()

I trigger this 30 seconds into mission start, my function is used to count how many units are active on the map (to work out how much load the server is under), as soon as it hits an Infantry M4 it craps out

THese units are going to be used for cargo in helis, they do not have #CARGO() in the names

"Try to add the variable MUnit.UnitName in that trace output. Let's see what names this is occurring on."

I did this yesterday, the unit names output are for eeach of the Infantry M4 guys, the names that are output are the original ME unit names eg Unit #048   etc etc

**Comment by shadowze** [comment] 2018-09-07 13:45
MUnit:GetDesc() , this returns nil for Infantry M4   unit, is this a DCS function or a moose one ?

**Comment by FlightControl-User** [comment] 2018-09-07 13:52
Really strange

**Comment by FlightControl-User** [comment] 2018-09-07 13:53
Are you sure that these aren't CARGO?

**Comment by FlightControl-User** [comment] 2018-09-07 13:55
@shadowze at the core it is a dcs function. But wanna see if the unit can be found, which is what GetDesc does first. If not found, nil is returned. How are these infantry created and what are the unit names?

**Comment by shadowze** [comment] 2018-09-07 13:55
as i posted in my message earlier

These units are going to be used for cargo in helis,  so yes
In helis controlled by players NOT as AI cargo stuff

**Comment by shadowze** [comment] 2018-09-07 14:00
so the task controller for the cargo task is renaming them and appending #CARGO to the group names

**Comment by shadowze** [comment] 2018-09-07 17:46
@shadowze at the core it is a dcs function. But wanna see if the unit can be found, which is what GetDesc does first. If not found, nil is returned. How are these infantry created and what are the unit names?

these are ME placed Infantry M4

names (unit names ?)    Unit #066  Unit #067 Unit #068 Unit #070  etc etc etc

**Comment by shadowze** [comment] 2018-09-07 17:51
the point that this function fails at is

			self:T3( { "Category:", MUnit:GetDesc().category, self.FilterMeta.Categories[CategoryName], CategoryName } )

because Infantry M4 returns nil for MUnit:GetDesc().category
line 13790 approx

    if self.Filter.Categories then
      local MUnitCategory = false
      for CategoryID, CategoryName in pairs( self.Filter.Categories ) do
	  
		if MUnit:GetDesc() ~= nil then
			env.info(" cat is " .. MUnit:GetDesc().category )
			self:T3( { "Category:", MUnit:GetDesc().category, self.FilterMeta.Categories[CategoryName], CategoryName } )
			
			if MUnit:GetDesc().category  and self.FilterMeta.Categories[CategoryName] and self.FilterMeta.Categories[CategoryName] == MUnit:GetDesc().category then
				MUnitCategory = true
			end
		else
		-- if we get there it must be Infantry M4 guy so just increment the count anyway
		MUnitCategory = true
		env.info(" CategoryID was " ..  CategoryID .. "    CategoryName was " .. CategoryName .. " name " .. MUnit:Name() )
		end	
		
      end
      MUnitInclude = MUnitInclude and MUnitCategory
    end

**Comment by FlightControl-User** [comment] 2018-09-07 19:58
Very weird

**Comment by FlightControl-User** [comment] 2018-09-07 19:58
I made a demo missing on the plane flying back home.

**Comment by FlightControl-User** [comment] 2018-09-07 19:59
One infantry group of 8, and a SET_UNIT object that counts 8 units of type M4 infantry

**Comment by FlightControl-User** [comment] 2018-09-07 19:59
Try yourself

**Comment by shadowze** [comment] 2018-09-08 09:35
no link to mission you created so no way to try it out

What I have done is to modify one of your existing demo missions that will indeed show this bug

I have PMed you it in Discord
TAD-CGO-007_-_Transport_Test_-_Cargo_Fun_show_bug.miz

**Comment by FlightControl-User** [comment] 2018-09-08 12:15
@shadowze @Delta-99 pushing a fix as we speak ...

**Comment by shadowze** [comment] 2018-09-08 13:13
ok having a go now

**Comment by shadowze** [comment] 2018-09-08 13:28
seems to be working great now, awesome work Sven

**Comment by Delta-99** [comment] 2018-09-08 16:27
Great to hear this was finally nailed down.

**Comment by FlightControl-User** [comment] 2018-09-08 19:55
It was my mistake, but finally we got it.

**Comment by shadowze** [comment] 2018-09-09 11:59
damn it, got this again today :-( , spoke too soon in closing it

**Comment by FlightControl-User** [comment] 2018-09-16 14:51
This is now fixed by the implementation of the FilterActive() method in SET_UNIT.

**Comment by FlightControl-User** [comment] 2018-09-29 11:57
OK. Closing. This is fixed.

**Closed by FlightControl-User** 2018-09-29 11:57 UTC
Labels: bug, fixed, ready for testing
