### ISSUE TITLE
Random Spawn options are broken in 2.5

### ISSUE THREAD

**Issue by neonbasschild** [FlightControl-Master/MOOSE#805] opened 2018-02-09 22:11 UTC
I have tried with 2.2 current and 2.3a items such as random templates or random spawn no longer look to be functioning. I have a group of ground troops that I have been using forever (1.5.6) and spawn zones that they normally spawn in.

in 2.5 they all just spawn were they are placed and not in random groups at all.

**Comment by thebgpikester** [comment] 2018-02-10 01:02
Your are going to have to provide **code**, _which_ functions are not working? Templates are working for me.

**Comment by neonbasschild** [comment] 2018-02-10 04:08
`
--Russian Troop Movement and Attack

ZoneTableAttack = { ZONE:New( "AZone" ), ZONE:New( "AZone1" ), ZONE:New( "AZone2" ), ZONE:New( "AZone3" ), ZONE:New( "AZone4" ), ZONE:New( "AZone5" ), ZONE:New( "AZone6" ) }
Attacktroops = { 'Attack Russian APC #001', 'Attack Russian APC #002', 'Attack Russian APC #003', 'Attack Russian APC #007', 'Attack Russian APC #008', 'Attack SA-10', 'Attack SA-10 #002', 'Attack SA-10 #003', 'Attack T-80 HQ', 'Attack T-80 Plt', 'Attack T-80 Supply' }
RU_CC = COMMANDCENTER:New( GROUP:FindByName( "Russian HQ" ), "Russian HQ" )

--AttackZone = ZONE:New( "Boarder" ) 
--BoarderBattle = ZONE_CAPTURE_COALITION:New( AttackZone, coalition.side.BLUE ) 

--[[function SCAN()
      RUSSIANGROUNDATTACK:scanUnits('enemy')
end]]

  RUSSIANGROUNDATTACK = autogft_Setup:new()
  RUSSIANGROUNDATTACK:setAdvancementTimer(300)
  RUSSIANGROUNDATTACK:startUsingRoads()
  RUSSIANGROUNDATTACK:addControlZone("Boarder")
  RUSSIANGROUNDATTACK:addControlZone("Town1")
  RUSSIANGROUNDATTACK:addControlZone("Town2")
  RUSSIANGROUNDATTACK:addControlZone("Town3")
  RUSSIANGROUNDATTACK:addControlZone("Town4")
  RUSSIANGROUNDATTACK:addControlZone("Town5")

  RUSSIANSAttack = SPAWN:New('Attack T-80 HQ')
  RUSSIANSAttack:InitLimit( 30, 0 )
  RUSSIANSAttack:InitRandomizeTemplate( Attacktroops )
  RUSSIANSAttack:InitRandomizeZones( ZoneTableAttack )
  RUSSIANSAttack:OnSpawnGroup(  function()
                                  RUSSIANGROUNDATTACK:scanUnits('Attack')
                                end)
  RUSSIANSAttack:SpawnScheduled( 600, 0.75 )
`

**Comment by neonbasschild** [comment] 2018-02-10 04:09
You can ignore the RUSSIANGROUNDATTACK code its for autogft. But the things that are not working is InitRandomizeTemplate and InitRandomizeZones

**Comment by neonbasschild** [comment] 2018-02-10 04:13
When using this code all the units spawn in nonrandom groups (aka they all spawn) and they all spawn at the location they are put on the map, not in any of the zones. If needed I can make up a video of what is happening. I also originally had it set up for 2.3a using InitRandomizeTemplatePrefixes

**Comment by Delta-99** [comment] 2018-02-11 06:56
Have not noticed this behavior in my missions.

**Comment by thebgpikester** [comment] 2018-02-11 11:02
You are mixing  **AutoGFT** with MOOSE. AutoGFT manages it's own spawning, this is not a MOOSE issue
AutoGFT is managed by Birger at https://github.com/birgersp/dcs-autogft
You can't mix two code bases and expect the same results.
Your code without AutoGFT runs fine.

**Comment by neonbasschild** [comment] 2018-02-11 17:35
What are you talking about? AutoGFT will spawn if you want it to but that is turned off. I use Moose for spawning and have autogft take over the units after spawning. 

This spawning issue is a moose error.

**Comment by Delta-99** [comment] 2018-02-11 19:22
Can you try commenting out the AutoGFT stuff completely. It is possible that the OnSpawnGroup is messing things up because of the AutoGFT. Shouldn’t but possible if RUSSIANGROUNDATTACK is not defined yet for some reason. 

Otherwise I have very similar code that works perfectly fine in pretty much any version of Moose going back a year.

**Comment by funkyfranky** [comment] 2018-02-11 22:08
@neonbasschild yes, as Delta99 said, could could you please give an example where Moose failed, i.e. without AutoGFT. Because this one is hard to reproduce.

**Comment by neonbasschild** [comment] 2018-02-12 04:25
I will make a video showing the bug. Please stand by.

**Comment by thebgpikester** [comment] 2018-02-14 10:45
hi @neonbasschild is there any update for this? The link above shows the basic  spawn in zone functions and they are still working when used on their own as per the example missions I linked, I'm quite sure that the AutoGFT scanning function you do when the OnSpawn is used is the reason the groups are deleted from their moose position and moved according to AutoGFT's scanning process. The reason I know that is because I was the one that worked extensively with the author of AutoGFT so I know how it works. Scanning simply deletes the existing unit and replaces it with an AutoGFT spawn. The two scripting processes WILL conflict in some situations but that aside, I can only say from the title of the Issue, there is not a problem with these functions as you stated and if you have found an issue via some interesting combination, then please follow up with MOOSE code only. I'll close this at the end of the week unless you have an update on this. FWIW i like that you tried to use both at once, it might have interesting possibilities.

**Comment by Delta-99** [comment] 2018-02-14 15:21
Agreed with @thebgpikester since we need to reproduce this with a simple example and I have no issues with the functionality in my scripts. We also need to clean up the issue list.

**Comment by neonbasschild** [comment] 2018-02-14 20:35
Close it, I am to busy to make a video right now.

**Comment by birgersp** [comment] 2018-02-15 17:03
I agree, it would be better to provide some script that is pure MOOSE, to isolate the problem.

But I think there's a little confusion here.

> You are mixing AutoGFT with MOOSE. AutoGFT manages it's own spawning, this is not a MOOSE issue
> AutoGFT is managed by Birger at https://github.com/birgersp/dcs-autogft
> You can't mix two code bases and expect the same results.
> Your code without AutoGFT runs fine apart from where you use RUSSIANGROUNDATTACK:scanUnits --> scanunits is not a MOOSE function its an AutoGFT function.

@thebgpikester While the code may appear intertwined, it really isn't. @neonbasschild is merely invoking a function when the units are spawned. Whatever `scanUnits` returns (or any function he would use instead, AutoGFT or whatever else) is irrelevant, as `OnSpawnGroup` doesn't use it.

With that said, I notice some other, possible issues with this script, unrelated to MOOSE. I'll hit you up in the chat @neonbasschild, and we can try to sort them out.

**Comment by Delta-99** [comment] 2018-02-16 16:14
@neonbasschild going to close this for now. We can re-open if / when @neonbasschild has a chance to provide a .miz showing this.

**Closed by Delta-99** 2018-02-16 16:14 UTC
Labels: can't reproduce
