### ISSUE TITLE
AI_A2A_Dispatcher:OnEventBaseCaptured Enhancement/Feature Request.

### ISSUE THREAD

**Issue by Zyfr** [FlightControl-Master/MOOSE#1317] opened 2020-05-03 04:26 UTC
Hiya, 

came across and edge case while playing around with the AI_A2A_DISPATCHER

Situation
1. Mission starts with airfield as NEUTRAL
2. Spawn in a REDFOR Ground Unit to capture the airfield
3. Setup the AI_A2A_DISPATCHER to create a REDFOR GCI/CAP 
4. Initially the GCI/CAP functions normally.. but after a while it stops working

Investigation: I notice that the base captured event is fired periodically in my logs - 
This in turn executes the AI_A2A_DISPATCHER:OnEventBaseCaptured function, 

Since there is no coalition change check executed - this stops any GCI/CAP from that airfield - even though the capturing coalition is the same coalition.

See log extract attached

```
2020-04-29 10:01:02.556 INFO    SCRIPTING: Executing script:  mc.spawnRedGnd({task="ground",tmpl="sa6", name="SA-6",minH=180, su=true})
2020-04-29 10:01:02.675 INFO    Scripting: event:t=29427.165,type=birth,initiatorMissionID=1000019,
2020-04-29 10:01:02.677 INFO    Scripting: event:t=29427.165,type=birth,initiatorMissionID=1000020,
2020-04-29 10:01:02.680 INFO    Scripting: event:t=29427.165,type=birth,initiatorMissionID=1000021,
2020-04-29 10:01:02.681 INFO    Scripting: event:t=29427.165,type=birth,initiatorMissionID=1000022,
2020-04-29 10:01:06.862 INFO    Scripting: event:type=base captured,place=Mozdok,t=29431.479,placeDisplayName=Mozdok,initiatorMissionID=1000019,

2020-04-29 10:24:51.869 INFO    Scripting: event:type=base captured,place=Mozdok,t=30856.479,placeDisplayName=Mozdok,initiatorMissionID=1000019,
2020-04-29 10:24:51.869 INFO    SCRIPTING: 113643(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Captured Mozdok)
2020-04-29 10:24:51.869 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN3 captured.)

2020-04-29 11:02:26.866 INFO    Scripting: event:type=base captured,place=Mozdok,t=33111.479,placeDisplayName=Mozdok,initiatorMissionID=1000019,
2020-04-29 11:02:26.867 INFO    SCRIPTING: 113643(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Captured Mozdok)
2020-04-29 11:02:26.867 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN3 captured.)

2020-04-29 11:03:44.550 INFO    SCRIPTING: Executing script:  mc.updateRedGci()
2020-04-29 11:03:44.550 INFO    SCRIPTING: Updating GCI SQN Configuration...
2020-04-29 11:03:44.550 INFO    SCRIPTING: Configuring SQN Mozdok SQN, Airfield: Mozdok
2020-04-29 11:03:44.550 INFO    SCRIPTING: Configuring SQN for GCI Mozdok SQN
2020-04-29 11:03:44.550 INFO    SCRIPTING: Configuring SQN for CAP Mozdok SQN
2020-04-29 11:03:44.550 INFO    SCRIPTING: 114320(    -1)/I:             AI_A2A_DISPATCHER03204.function({[CAP]={[1]=Mozdok SQN,[2]=1111.2,[3]=2222.4,[4]=3048,[5]=9144,[6]={[Vec2]={[y]=833025.41647664,[x]=-84653.599271459,},[ClassName]=ZONE_RADIUS,[Radius]=37040,},[7]=648.2,[8]=1018.6,[9]=3048,[10]=9144,[11]=BARO,[12]=BARO,},})

2020-04-29 11:43:01.866 INFO    Scripting: event:type=base captured,place=Mozdok,t=35546.479,placeDisplayName=Mozdok,initiatorMissionID=1000019,
2020-04-29 11:43:01.866 INFO    SCRIPTING: 113643(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Captured Mozdok)
2020-04-29 11:43:01.866 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN captured.)
2020-04-29 11:43:01.866 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN3 captured.)

2020-04-29 12:18:16.866 INFO    Scripting: event:type=base captured,place=Mozdok,t=37661.479,placeDisplayName=Mozdok,initiatorMissionID=1000019,
2020-04-29 12:18:16.867 INFO    SCRIPTING: 113643(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Captured Mozdok)
2020-04-29 12:18:16.867 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN captured.)
2020-04-29 12:18:16.867 INFO    SCRIPTING: 113650(  7211)/I:             AI_A2A_DISPATCHER03204.EventFunction(Squadron Mozdok SQN3 captured.)
```

Can we implement a Coalition check prior to disabling the Defender Squadron

e.g. Using the SpawnTemplate to figure out the Defender Coalition
```
  --- Event base captured.
  -- @param #AI_A2A_DISPATCHER self
  -- @param Core.Event#EVENTDATA EventData
  function AI_A2A_DISPATCHER:OnEventBaseCaptured( EventData )
    local AirbaseName = EventData.PlaceName -- The name of the airbase that was captured.
    self:I( "Captured " .. AirbaseName )
    -- Now search for all squadrons located at the airbase, and sanatize them.
    for SquadronName, Squadron in pairs( self.DefenderSquadrons ) do
      if Squadron.AirbaseName == AirbaseName then
        if Squadron.Coalition == nil then
          local DefenderSqnGroup = nil
          local TemplatePrefixes = Squadron.TemplatePrefixes
          if type( TemplatePrefixes ) == "string" then
            local SpawnTemplate = TemplatePrefixes
            DefenderSqnGroup = GROUP:FindByName(SpawnTemplate)
          else
            for TemplateID, SpawnTemplate in pairs( TemplatePrefixes ) do
              DefenderSqnGroup = GROUP:FindByName(SpawnTemplate)
              break
            end
          end
          Squadron.Coalition = DefenderSqnGroup:GetCoalition()
        end
        if Squadron.Airbase:GetCoalition() ~= Squadron.Coalition then
          Squadron.ResourceCount = -999 -- The base has been captured, and the resources are eliminated. No more spawning.
          Squadron.Captured = true
          self:I( "Squadron " .. SquadronName .. " captured." )
        else
          self:I( "Base Captured Event detected but Coalition is still the same as assigned Defender SQN" )
        end
      end
    end
  end
```

**Comment by thebgpikester** [comment] 2020-06-25 18:10
https://forums.eagle.ru/showthread.php?t=215185
I've seen other threads but I cannot for the life of me find them after 15 mins. Point is, this is a DCS bug. And I'm not even sure if it is reported/properly understood/WonFix/alreadyFixedinVersion etc.

I agree with the premise that events in multiplayer are worse than bad, there are more bugs. But right now, based on the information and hunches, I'm not inclined to refactor the code until I get a good feeling for if ED will fix it or wont fix it and if the issue is what I think it is. Because there's no sample mission to reproduce on (despite me absolutely believing you)
So I'm going to consider in this order:
Reproducing
Reporting
Coming back based on feedback to this after discussion with Frank.

**Comment by thebgpikester** [comment] 2020-06-25 19:07
https://forums.eagle.ru/showpost.php?p=4245133&postcount=2
Seems acknowledged with little chance of a fix, like most DCS events.

So... design. The event system triggers the check. But, if there is no event trigger then nothing changes. And if there is a bug firing these triggers randomly in multiplayer, then checking only on the event is worthless and detrimental. It also assumes that it's just the bug and not a momentary flip of the base possesion. If the base does, then the workaround could theoretically not work anyway. Leaving scheduled checking... I dunno really this is crap :(

**Comment by funkyfranky** [comment] 2020-06-25 20:36
I guess a fix would be to add a coalition parameter to the A2A dispatcher as you suggest and check if the base was captured by any other coalition.

Anyway, thanks for the report. I was not aware of this DCS bug.

**Closed** 2020-12-29 22:46 UTC
Labels: DCS bug, Low Prio, Provide Miz File, Question, Todo
