### ISSUE TITLE
Error in Eventhandler on unit hit

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#361] opened 2017-03-26 20:40 UTC
Code is a follows;
`--Set Battalion HQ Company
local twothirdBatHQ = GROUP:FindByName("HQ 23rd Lt Inf Bat")
--BASE:T({"Created HQ Group", twothirdBatHQ})
local twothirdBatHQZone = ZONE_GROUP:New("23rdBatHQZone", twothirdBatHQ, 300)

--Set Event list
twothirdBatHQ:HandleEvent( EVENTS.Hit )
function twothirdBatHQ:OnEventHit( EventData )
 MESSAGE:New("HQ is taking taking fire",10,"Incoming Comms Bat HQ"):ToAll()
--twothirdBatHQ:GetRadio():NewUnitTransmission("BattTakingfire.ogg", "Tank taking heavy damages down here, help us !",  8, 122, radio.modulatio.AM, false):Broadcast()
end`

Get the following error in log which I believe is a result of an error in the eventhandler

`01947.315 INFO    SCRIPTING:   5051(    13)/E:               EVENT00000.onEvent({[1]="Calling OnEventHit for GROUP ",[2]="GROUP#000000016",[3]=4,})
01947.315 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:13509: attempt to call method 'getPosition' (a nil value)
01947.315 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:4791: in function 'getPosition'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:13509: in function 'GetPointVec2'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:12869: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:12864>
	(tail call): ?
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00006A06"]:10: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00006A06"]:8>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00000D41"]:5054: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>`

Occurs when unit is hit

**Comment by Grey-Echo** [comment] 2017-03-27 08:56
This problem is caused by issue #362. I'm currently working on a fix, will be fixed soon.

**Closed** 2017-03-27 10:27 UTC
Labels: fixed
