### ISSUE TITLE
AI_A2A_Dispatcher: DisengageRadius is not being observed by AI. 

### ISSUE THREAD

**Issue by CSG1-Shogun** [FlightControl-Master/MOOSE#933] opened 2018-06-26 00:35 UTC
I have done a number of testing around this, and the AI just does not observe the DisengageRadius. I have set the parameter to 55560 meters, which is 30nm. I have been chased as far as 100nm (about 185,000m) until the AI runs out of fuel then crashes. 

In the test mission uploaded below, I have an F18 outside Khasab that will cross the border, get GCI or CAP engagement, and then burn out back across and to the bottom of the map. The AI will continue to pursue it. My code:<br />
<br />
DetectionSetGroup = SET_GROUP:New()  <br />
DetectionSetGroup:FilterPrefixes( { "Iran EWR" } ) <br />
DetectionSetGroup:FilterStart() <br />
Detection = DETECTION_AREAS:New( DetectionSetGroup, 50000 )<br />
A2ADispatcher = AI_A2A_DISPATCHER:New( Detection )<br />
IranBorderZone = ZONE_POLYGON:New( "Iran Border", GROUP:FindByName( "Iran Border" ) )<br />
A2ADispatcher:SetBorderZone( IranBorderZone )<br />
A2ADispatcher:SetDisengageRadius( 55560 )<br />
A2ADispatcher:SetEngageRadius( 92600 )<br />
A2ADispatcher:SetGciRadius( 138900 )<br />
<br />
A2ADispatcher:SetTacticalDisplay( true )<br />
<br />
-- Setup the squadrons.<br />
A2ADispatcher:SetSquadron( "Bandar Lengeh", "Bandar Lengeh", { "Iran Mig21", "Iran Mig29" } )<br />
A2ADispatcher:SetSquadron( "Bandar Abbas", "Bandar Abbas Intl", { "Iran Mig29", "Iran Mig21" } )<br />
A2ADispatcher:SetSquadron( "Lar Airbase", "Lar Airbase", { "Iran Mig29", "Iran Mig21" } )<br />
<br />
-- Setup the overhead<br />
A2ADispatcher:SetSquadronOverhead( "Bandar Abbas", 1 )<br />
A2ADispatcher:SetSquadronOverhead( "Bandar Lengeh", 1 )<br />
A2ADispatcher:SetSquadronOverhead( "Lar Airbase", 1 )<br />
<br />
-- Setup the Grouping<br />
A2ADispatcher:SetSquadronGrouping( "Bandar Abbas", 2 )<br />
A2ADispatcher:SetSquadronGrouping( "Bandar Lengeh", 2 )<br />
A2ADispatcher:SetSquadronGrouping( "Lar Airbase", 2 )<br />
<br />
-- Setup the Takeoff methods<br />
A2ADispatcher:SetSquadronTakeoffInAir( "Bandar Abbas" )<br />
A2ADispatcher:SetSquadronTakeoffInAir( "Bandar Lengeh" )<br />
A2ADispatcher:SetSquadronTakeoffInAir( "Lar Airbase" )<br />
<br />
-- Setup the Landing methods<br />
A2ADispatcher:SetSquadronLandingAtEngineShutdown( "Bandar Abbas" )<br />
A2ADispatcher:SetSquadronLandingAtEngineShutdown( "Bandar Lengeh" )<br />
A2ADispatcher:SetSquadronLandingAtEngineShutdown( "Lar Airbase" )<br />
<br />
--Fuel use
A2ADispatcher:SetSquadronFuelThreshold( "Bandar Abbas", .20 )<br />
A2ADispatcher:SetSquadronFuelThreshold("Bandar Lengeh", .20 )<br />
A2ADispatcher:SetSquadronFuelThreshold("Lar Airbase", .20 )<br />
<br />
-- CAP Squadron execution.
CAPZoneSouth = ZONE_POLYGON:New( "IranCAPSouth", GROUP:FindByName( "IranCAPSouth" ) )<br />
CAPZoneEast = ZONE_POLYGON:New( "IranCAPEast", GROUP:FindByName( "IranCAPEast" ) )<br />
CAPZoneWest = ZONE_POLYGON:New( "IranCAPWest", GROUP:FindByName( "IranCAPWest" ) )<br />
<br />
A2ADispatcher:SetSquadronCap( "Bandar Lengeh", CAPZoneSouth, 4000, 8000, 500, 800, 900, 1200, "BARO" )<br />
A2ADispatcher:SetSquadronCap( "Bandar Abbas", CAPZoneEast, 4000, 8000, 500, 800, 900, 1200, "BARO" )<br />
A2ADispatcher:SetSquadronCap( "Lar Airbase", CAPZoneWest, 4000, 8000, 500, 800, 900, 1200, "BARO" )<br />
<br />
A2ADispatcher:SetSquadronCapInterval( "Bandar Abbas", 1, 90, 300, 1 )<br />
A2ADispatcher:SetSquadronCapInterval( "Bandar Lengeh", 1, 90, 300, 1 )<br />
A2ADispatcher:SetSquadronCapInterval( "Lar Airbase", 2, 90, 300, 1 )<br />
<br />
-- GCI Squadron execution.<br />
A2ADispatcher:SetSquadronGci( "Bandar Abbas", 900, 1200 )<br />
A2ADispatcher:SetSquadronGci( "Bandar Lengeh", 900, 1200 )<br />
A2ADispatcher:SetSquadronGci( "Lar Airbase", 900, 1200 )<br />
<br />
<br />
Mission File: [DisengageRangeTestFail.zip](https://github.com/FlightControl-Master/MOOSE/files/2135130/DisengageRangeTestFail.zip)

**Comment by FlightControl-User** [comment] 2018-06-26 04:49
Yes. I've seen a similar issue in the log. Something to be looked at.

**Comment by thebgpikester** [comment] 2018-06-26 08:18
Can you resubmit the miz without the mod so I can verify please, as it won't load due to Navy deck crew mod. Also, github takes the miz format, so no need to rename to zip. I'd like to look at this because I have good experience of the module without the setting.

**Comment by CSG1-Shogun** [comment] 2018-06-26 14:57
Hi @thebgpikester , 

I have edited the miz to remove all everything mod related- doesn't list it as a required mod now. Apologies.

However, I still can't get GitHub to let me upload the file.  It says "We don't support that file type. Try again with a GIF, JPEG, JPG, PNG, DOXC, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP." I tried IE, Chrome, and FF to no avail. 

I went ahead and uploaded it to my own file server:

[DisengageRangeTestFail-ModObjectsDeleted.miz](http://csg1modpack.net/DisengageRangeTestFail-ModObjectsDeleted.miz)

Thanks!

**Comment by thebgpikester** [comment] 2018-06-26 18:44
great I got it. Can confirm that the Task to engage them remains up, but I need to play around with the distances to determine the exact fail.

**Comment by thebgpikester** [comment] 2018-06-26 19:19
Found something. I set the distance to 555 and the chasing flight disengaged around the 34nm mark. I think this might be a maths bug, but yet to work out exactly what. Still working

**Comment by thebgpikester** [comment] 2018-06-26 19:56
OK results are all over the place. I set the numbers to 
100 - RTB after 20nm
200 - RTB after 30nm
300 - RTB after 10nm
300 - Never rtb'd and chased
Looked through the code the only way I can see it failing is via an FSM fail somehow, but we need FC to have a look.
It's definitely not consistent or according to docs, for sure.

**Comment by CSG1-Shogun** [comment] 2018-06-26 19:58
Thanks for the help testing this! If there is anything I can do to help recreate or test, please let me know.

**Comment by thebgpikester** [comment] 2018-06-28 00:32
Duplicate of #823 
reproduced.
Closing as duplicate.

**Closed by thebgpikester** 2018-06-28 00:32 UTC
Labels: bug, duplicate
