### ISSUE TITLE
A2A_Dispatcher ignores CAP limit if resources are unlimited.

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#938] opened 2018-06-29 15:32 UTC
CAP aircraft keep spawning if not parameter for resources is given in A2ADispatcher:SetSquadron() function.
However, if a parameter for resources is given (also a very large one like 999) the CAP limit is acknowledged.

```
Sample code
  DetectionSetGroup = SET_GROUP:New()
  DetectionSetGroup:FilterPrefixes({ "Red AWACS" })
  DetectionSetGroup:FilterStart()
  
  local Detection = DETECTION_AREAS:New(DetectionSetGroup, 30000)
  
  -- Setup the A2A dispatcher, and initialize it.
  A2ADispatcher = AI_A2A_DISPATCHER:New(Detection)
  
  local LarAB=AIRBASE:FindByName(AIRBASE.PersianGulf.Lar_Airbase)
  LarAB:MarkParkingSpots()
  
  
  -- Turn on tactical display.
  A2ADispatcher:SetTacticalDisplay(true)
  
  -- Setup the squadrons.  
  A2ADispatcher:SetSquadron("Lar Airbase", AIRBASE.PersianGulf.Lar_Airbase, {"Red MiG29 Alpha"})
  
  local CAPZoneAlpha = ZONE_POLYGON:New("Red CAP Zone Alpha", GROUP:FindByName("Red CAP Zone Alpha"))
  
  A2ADispatcher:SetSquadronCap("Lar Airbase", CAPZoneAlpha, 4000, 8000, 600, 800, 800, 1200)
  A2ADispatcher:SetSquadronTakeoffFromParkingCold("Lar Airbase")
  --A2ADispatcher:SetSquadronTakeoffFromRunway("Lar Airbase")
  A2ADispatcher:SetSquadronCapInterval("Lar Airbase", 2, 10, 30, 1)
  A2ADispatcher:SetDefaultCapLimit(2)
  A2ADispatcher:SetSquadronGrouping( "Lar Airbase", 4)
```

**Comment by FlightControl-User** [comment] 2018-09-30 05:42
Hi frank, this was done by design. So if there is no parameter given, it is meant to have unlimited resources.

**Comment by FlightControl-User** [comment] 2018-09-30 05:43
I will close this issue, ok? Unless you think i should not :-) @funkyfranky

**Closed** 2018-09-30 05:43 UTC
Labels: Not a bug
