### ISSUE TITLE
TASK_A2G doesn't report correctly and crashes execution of COMMANDCENTER Birth event handler

### ISSUE THREAD

**Issue by victorcotap** [FlightControl-Master/MOOSE#895] opened 2018-05-08 04:42 UTC
branch `Topper`, tracking develop
/!\ Check my commit 28351f2cad4da561b6cec9c3c93417ed261463fe which fixes a previous issue relative to this (AFAIK)

After a long server runtime (24h), joining a slot does trigger the S_EVENT_BIRTH event but instead of being greeted by the different Missions reporting their current task, you get nothing and the error below.

Menus are still present. Asking for my A2A mission to report tasks will work. Asking for my A2G mission to report crashes the script exactly the same way as S_EVENT_BIRTH.
This renders the A2G Task Dispatcher and mission unusable.

It seems like it simply cannot find `Info` within TaskInfo on GetData

```lua
2018-05-08 04:17:27.604 INFO    SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/Tasking/TaskInfo.lua"]:87: attempt to index local 'Object' (a nil value)
2018-05-08 04:17:27.604 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/Event.lua"]:738: in function <[string "Scripts/Moose/Core/Event.lua"]:734>
	[string "Scripts/Moose/Tasking/TaskInfo.lua"]:87: in function 'GetData'
	[string "Scripts/Moose/Tasking/Task_A2G.lua"]:299: in function 'ReportOrder'
	[string "Scripts/Moose/Tasking/Mission.lua"]:933: in function <[string "Scripts/Moose/Tasking/Mission.lua"]:933>
	(tail call): ?
	[C]: in function 'sort'
	[string "Scripts/Moose/Utilities/Utils.lua"]:399: in function 'spairs'
	[string "Scripts/Moose/Tasking/Mission.lua"]:933: in function 'ReportSummary'
	[string "Scripts/Moose/Tasking/CommandCenter.lua"]:568: in function 'ReportSummary'
	[string "Scripts/Moose/Tasking/CommandCenter.lua"]:111: in function <[string "Scripts/Moose/Tasking/CommandCenter.lua"]:102>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Event.lua"]:1011: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

**Comment by thebgpikester** [comment] 2018-07-04 12:08
Can't reproduce this. This is quite complex due to the timing. Not sure how to deal with it. ANy menu issues I have solved by swapping slot and back, so it's not that.

**Comment by FlightControl-User** [comment] 2018-09-29 13:47
Guys, sorry, this is an impossible bug report for me to fix now... I will postpone to the future, and please review and react, otherwise i'll close this. these reports are working.

**Comment by FlightControl-User** [comment] 2018-09-29 13:48
@victorcotap please read the above comment ... can i close?

**Closed by FlightControl-User** 2018-09-29 13:48 UTC
Labels: bug, can't reproduce
