### ISSUE TITLE
TSK-A2G DISPATCH Task aborting not successful until all clients abort

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#486] opened 2017-04-27 04:27 UTC
TEST CASE: Client 1 and Client 2 join same task BAI001.  Client 2 aborts task.  No aborted task confirmation is sent to Client 2.  When Client 1 aborts, Aborted task confirmation message is sent to both clients.  Could be confusing for MP players.

**Comment by FlightControl-Master** [comment] 2017-04-27 10:31
For a reason unkniwn, S_EVENT_PLAYER_ENTER_UNIT is not fired on the server. So there is no way to know which player is in which unit...

**Comment by FlightControl-Master** [comment] 2017-04-27 10:32
Forget TASKING

**Comment by Whiplash822** [comment] 2017-04-27 20:23
using DCS 2.0 I can confirm that the player name is listed in the task status report. The screen shot only shows my name however, when I was logged in with d0o0m it also showed his name in the list.
![screen_170427_124144](https://cloud.githubusercontent.com/assets/25238456/25502728/b0a74228-2b4c-11e7-859a-060ffdcd0c0e.jpg)

**Comment by FlightControl-Master** [comment] 2017-04-27 20:32
And that is your name on a client machine where you are logged in? That gives hope... So i can further test with 2.0

**Comment by FlightControl-Master** [comment] 2017-04-27 20:33
To ensure, this picture is taken on the client machine, not on the server and you whiplash is your helo?

**Comment by Whiplash822** [comment] 2017-04-27 20:41
let me clarify, the picture was taken from my machine which was hosting a DCS 2.0 multiplayer server. However, testing last night I was a client on a server that d0o0ms machine was hosting. I can most definitely assure you that those are our client names. The report only shows my name in the screen shot because no one else was logged in. Last night when d0o0m and I we logged onto the server he was hosting both of our client names appeared in the task status list.

**Comment by FlightControl-Master** [comment] 2017-04-27 20:43
Suggest you do a test again. Just the mission on your machine, but start in spectators. Let dooom join from a client. Accept a task. And let him run the status report. Is his name shown?

**Comment by Whiplash822** [comment] 2017-04-27 20:46
ok we can do that tonight, d0o0m is not active at the moment.

**Comment by Whiplash822** [comment] 2017-04-28 06:02
Here is a screenshot from tonight's test with d0o0m and myself listed under the task status report. Both names listed are our client names on the server.
![screen_170427_215131](https://cloud.githubusercontent.com/assets/25238456/25516134/8ce2343c-2b9d-11e7-9626-d3399003e8c4.jpg)

**Comment by FlightControl-Master** [comment] 2017-05-02 04:00
This is WONDERFUL! So that proves that the TASKING works under DCS World 2!!!

**Comment by FlightControl-Master** [comment] 2017-05-02 09:03
Guys, I've been testing now also with @thebgpikester on NTTR. We are unable to do what you are doing. It just is not working.

Can you please BOTH do the following @d0o0m @Whiplash822:

- [ ] 1. Show me your version number of DCS world that you have currently installed. Ours is 2.0.5.3889. 
- [ ] 2. Do you have a firewall setup or anything?

Sven

**Comment by d0o0m** [comment] 2017-05-02 15:01
Hey FC... i tried booting up 2.0 alpha today to get that version #... unfortunately, the updater is trying to run before I can snag the version # currently installed.  Is there a way i can boot 2.0 without triggering the updater?
Sorry for the silly question.

As for firewall, I am using Windows Firewall only on this machine.  My server/client machine is hardlined straight to the modem and bypasses any routers.  

I am pretty sure I have CA installed but i'll check.

**Comment by d0o0m** [comment] 2017-05-02 16:18
nevermind - im an idiot... i just ran run.exe out of the install directory to bypass the updater.  i was on 2.0.5.3889 when we did the testing.
i have CA installed.
Note that when we were testing MP, we were only using two PC... there was no third server PC in the mix.

**Comment by FlightControl-Master** [comment] 2017-05-02 17:02
What is really confusing is that it seems to work in your installation... If you take the files from the video and run this in your environment, does it work then? Maybe the root cause is not with dcs but something else?

https://www.youtube.com/watch?v=Un9S67NDoLg

**Comment by FlightControl-Master** [comment] 2017-05-02 17:04
The mission can be found here...

https://github.com/FlightControl-Master/BUG_REPORT_MISSIONS/tree/master/BUG-001%20-%20S_EVENT_PLAYER_ENTER_UNIT

**Comment by FlightControl-Master** [comment] 2017-05-02 17:06
@d0o0m your last sentence is confusing. Was it a client server setup? So one pc connecting to the other pc? That is sufficient.

**Comment by d0o0m** [comment] 2017-05-02 17:24
yes - it was a client server setup.. my machine was both the server and hosted my client while whiplash connected from his PC.

I'll try that mission today before updating 2.0

**Comment by FlightControl-Master** [comment] 2017-05-02 18:41
There version you have 2.0.5.3889 is the one where i am having this issue. Have a careful watch to the video. And try to simulate on you environment in a client server setup. Even if you run this only on the server with a local user, you should have a blank user name...

**Comment by FlightControl-Master** [comment] 2017-05-04 03:57
I think I FOUND something... The event BIRTH is fired when a player enters a PLANE or a HELICOPTER... In that case, the logic will work. getPlayerName() seems to work in MP for air units... Not for CA units...
So in other words, i can debug the tasking further today, but it will only be for air units. Ground units won't be functional.

**Comment by FlightControl-Master** [comment] 2017-05-04 04:04
@d0o0m @Whiplash822 This was done by design ...
You see, a transition from a TASK status to **abort** is decoupled from a player abort the task **execution** ... That being said, when a player aborts a task, a message should be sent to all players within the assignment group of the task. But the task should only get to status abort, when all players aborted the task. And this is actually a difficult one... I need to think about this one a bit ...

**Comment by FlightControl-Master** [comment] 2017-05-04 04:08
This is the logic that is executed currently at the abort cycle...

```lua
function TASK:AbortUnit( PlayerUnit )
  self:F( { PlayerUnit = PlayerUnit } )
  
  local PlayerUnitAborted = false
  
  local PlayerGroups = self:GetGroups()
  local PlayerGroup = PlayerUnit:GetGroup()

  -- Is the PlayerGroup part of the PlayerGroups?  
  if PlayerGroups:IsIncludeObject( PlayerGroup ) then
  
    -- Check if the PlayerGroup is already assigned to the Task. If yes, the PlayerGroup is aborted from the Task.
    -- If the PlayerUnit was the last unit of the PlayerGroup, the menu needs to be removed from the Group.
    if self:IsStateAssigned() then
      local IsAssignedToGroup = self:IsAssignedToGroup( PlayerGroup )
      self:E( { IsAssignedToGroup = IsAssignedToGroup } )
      if IsAssignedToGroup then
        local PlayerName = PlayerUnit:GetPlayerName()
        self:UnAssignFromUnit( PlayerUnit )
        self:MessageToGroups( PlayerName .. " aborted Task " .. self:GetName() )
        self:E( { TaskGroup = PlayerGroup:GetName(), GetUnits = PlayerGroup:GetUnits() } )
        if #PlayerGroup:GetUnits() == 1 then
          self:UnAssignFromGroup( PlayerGroup )
          PlayerGroup:SetState( PlayerGroup, "Assigned", nil )
        end
        self:Abort()
        self:PlayerAborted( PlayerUnit )
      end
    end
  end
  
  return PlayerUnitAborted
end
```

You see that only at the last unit the abort is executed... Maybe this needs to be changed ...
This is a good post guys! Fantastic! Puts me into the thinking mode again :-)

**Comment by FlightControl-Master** [comment] 2017-05-05 10:52
This is fixed now and heavily debugged.
Aborting a task is only executed, when the last assigned group aborts a task.

For example:

Client A joins task X
Client B joins task X
Client A aborts task X. Task X is still assigned.
Client B aborts task X. Task X is aborted and will be replanned.

**Closed by FlightControl-Master** 2017-05-05 10:52 UTC

**Comment by FlightControl-Master** [comment] 2017-05-05 10:53
Just note, in certain cases there is a pending issue with the assigned menu hanging. The logic internally works, but the assigned menu should be removed, and it isn't. I need to put my head around that once... But am too tired now.
