### ISSUE TITLE
Something went wrong in the event handling system (OnEventBirth)

### ISSUE THREAD

**Issue by ojemineh** [FlightControl-Master/MOOSE#2038] opened 2023-11-16 23:44 UTC
I just wanted to continue working on a mission and stumbled upon something...

Before update 2.9.1.48111 (DCS) you could use the following example to find out the spawn of a unit (OnEventBirth) and then do nice things with the information received.

![Code_RLkANswPy8](https://github.com/FlightControl-Master/MOOSE/assets/47060189/efa8200e-89ac-4e34-8a3c-b77aa949c8cd)

But that doesn't work anymore. NOW you get a strange number returned. but only if you replace "EventData.**IniUnit**" with "EventData.**initiator**", since "IniUnit" is always NIL.

![notepad++_XXjQpMpMCu](https://github.com/FlightControl-Master/MOOSE/assets/47060189/0dc1dae5-8cc4-4f83-a28c-9d06bd44f874)

maybe moose needs to be adjusted? or maybe the problem is total on eagle dynamics? 
bug or feature? I don't know!

**Comment by funkyfranky** [comment] 2023-11-16 23:59
Caused by a change in DCS API `getCategory` behaviour. Should be fixed in latest Moose.lua from master or develop branch.
Please update!

**Comment by xanstin** [comment] 2023-11-17 04:18
I downloaded the 2.9.1 Moose file is this the one you are referring to or is it a different one? I still am having the issue with event handling.

**Comment by ojemineh** [comment] 2023-11-17 04:40
> I downloaded the 2.9.1 Moose file is this the one you are referring to or is it a different one? I still am having the issue with event handling.

![firefox_ZCIbiYVkE3](https://github.com/FlightControl-Master/MOOSE/assets/47060189/5992aa79-f450-4723-99fc-9c1ed5025bae)

You won't find the version he means in the releases. In the "code view" you will find a green button on the right side of the website. So you basically have to create a “build” by yourself.

**Closed** 2023-11-17 04:41 UTC
Labels: Enhancement, Fix Implemented
