### ISSUE TITLE
Zone apears to be nil when gives as part of array

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#376] opened 2017-03-30 11:30 UTC
When give `ForEachGroupCompletelyInZone(myZon[x], function(MooseGroup)` it apears like the ForEachGroupCompletelyInZone returns _nil_ 
Here is error log:
```
00246.746 INFO    SCRIPTING:     47(    -1)/E:                BASE00000.function(redsoldier is greater 0)
00246.746 INFO    SCRIPTING: Error in timer function: [string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:16624: attempt to call method 'IsVec3InZone' (a nil value)
00246.746 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:3976: in function 'IsVec3InZone'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:16624: in function 'IsCompletelyInZone'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:8884: in function 'Function'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:8498: in function 'co'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:8518: in function 'Schedule'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:8532: in function 'ForEach'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis000013DD"]:8880: in function 'ForEachGroupCompletelyInZone'
	[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis00002129"]:48: in function <[string "C:\Users\thor\AppData\Local\Temp\DCS\/~mis00002129"]:36>
```

**Comment by Grey-Echo** [comment] 2017-03-30 15:46
Same thing, edited your issue to make the log more readable !

**Comment by FlightControl-Master** [comment] 2017-03-31 08:56
This is normal and is not a bug. The method has not been understood. This is an iterator, not an IF evaluation function... 

Let me see if I can find the correct method that needs to be used! @baluballa

**Comment by FlightControl-Master** [comment] 2017-03-31 08:59
But I am really confused what is the functional goal you want to achieve. I mean, the ForEachGroupCompletelyInZone will call the function, providing the MooseGroup for those groups that are completely in the zone ... What is wrong with this function? Can you confirm? I am parking this one until further notice. @baluballa

**Comment by baluballa** [comment] 2017-03-31 09:17
I don't understand this my-selves but i I change the parameter given as a part of an array, it gives me the supplied log as error. If I change the parameter to and single variable like `ForEachGroupCompletelyInZone(myZone, function(MooseGroup)` I don't get the error. However, then the script fails, if there is no group within the zone. This is reported in github in my other report.

ZONE array is created like this:
` local zonesToOccupy = {"MEDIA TOWER", "ELECTRIC FACILITY", "TRAIN STATION", "BRIDGE CHOPPER 2", "BRIDGE CHOPPER 1"}
  BASE:E("Creating Zones")
  for index, value in ipairs(zonesToOccupy) do -- Make Moose zones from ME zones...
    BASE:E({"Creating Zone", value})
    mooseWrapZones[index] = ZONE:New(value)
  end`

And no there might be _no groups_ within the zone, but the SET is _NOT empty_ for sure. I am currently investing this my selves. 

The goal is to count how many units are within a particular ZONE. ZONE is not empty... 

Hope this clarify...

**Comment by Grey-Echo** [comment] 2017-03-31 09:25
Updated your post for readability.
Removed the possible bug label since this is clearly a user error.

If I understand well, you have a table of ZONEs and you want to count how many UNITs are in any of the ZONEs. Correct ?

**Comment by baluballa** [comment] 2017-03-31 09:34
Yes

**Comment by Grey-Echo** [comment] 2017-03-31 10:05
Ok. Here is a bit of code to help you achieve what you want. It's untested and you're gotta want to tweak it, but it should get you started:

``` lua
local zonesToOccupy = {"MEDIA TOWER", "ELECTRIC FACILITY", "TRAIN STATION", "BRIDGE CHOPPER 2", "BRIDGE CHOPPER 1"}
local mySet = SET_GROUP:New()
mySet:AddGroupByName("GroupName1"):AddGroupByName("GroupName2") -- Add your GROUPs to the SET_GROUP here !

local NumberOfUnitsInZones = 0

for i=1, zonesToOccupy.getn() do -- For each zone
	mySet:ForEachGroupPartlyInZone(zonesToOccupy[i],  -- For each Group of MySet partly in zone i
		function(Group)
			if Group:IsParltyInZone(zonesToOccupy[i]) then  -- If there is at least on Unit of Group in zone i
				for j=1, Group:GetSize() do  -- For each Unit of the Group
					if Group:GetUnit(j):IsInZone(zonesToOccupy[i]) then -- If it is in the zone i
						NumberOfUnitsInZones = NumberOfUnitsInZones + 1 -- One more Unit in the zone array !
					end
				end
			end
		end
	)	
end
```

I'm closing the issue. Join us on Slack if you need more help for you mission !

**Closed by Grey-Echo** 2017-03-31 10:05 UTC
Labels: invalid

**Comment by baluballa** [comment] 2017-03-31 10:19
Im Wingthor in slack, currently working with flightcontrol. I have a look at your code... Thanks,

**Comment by FlightControl-Master** [comment] 2017-03-31 12:27
What to do with this issue?
