### ISSUE TITLE
CARGO has no method FindByName

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#788] opened 2017-12-31 18:23 UTC
FindByName is used in SET_CARGO:AddCargosByName( AddCargoNames ) as CARGO:FindByname(). But CARGO has no such function.

**Comment by FlightControl-User** [comment] 2018-02-18 11:18
@funkyfranky Where did you detect this Frank? I will look into it, but need to understand a bit more context. Can you help me?

**Comment by funkyfranky** [comment] 2018-02-19 10:51
@FlightControl it's been a while. I don't know exactly where I encountered this. Maybe in TASK_CARGO.
If you look in to the SET_CARGO:AddCargosByName( AddCargoNames ) function, you will find CARGO:FinByName().
As far as I could tell, the CARGO class does not have the function FindByName. It has CARGO:New().
But maybe I'm overlooking something....

**Comment by FlightControl-User** [comment] 2018-03-03 06:14
It is by design. CARGO was never meant to be attached directly to DCS objects, it can be, but it also cannot.
You see, I wanted CARGO to be "virtual". There is somewhere in the mission CARGO alive, and there is a "carrier" of cargo. So, cargo could either be a visual object within the sim (like infantry, or cargo static objects), or, it could be "virtual" like within an object carried (f.e. a letter, a box, a delivery....).
That is why there is only a :New() method on CARGO, not a FindByName().

**Comment by FlightControl-User** [comment] 2018-03-06 14:33
Closing this.

**Closed** 2018-03-06 14:35 UTC
Labels: invalid
